/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Alpha_shape_2;
import CGAL.Kernel.Weighted_point_2; import CGAL.Kernel.Ref_int; import CGAL.Kernel.Segment_2; import CGAL.Kernel.Triangle_2; import CGAL.Kernel.Oriented_side; import CGAL.Triangulation_2.Locate_type; import CGAL.Triangulation_2.Ref_Locate_type_2; import java.util.Iterator; import java.util.Collection;
public class Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_Alpha_shape_2JNI.delete_Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2() {
    this(CGAL_Alpha_shape_2JNI.new_Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2(), true);
  }

  public void clear() {
    CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_clear(swigCPtr, this);
  }

  public int dimension() {
    return CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_dimension(swigCPtr, this);
  }

  public int number_of_vertices() {
    return CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_number_of_vertices(swigCPtr, this);
  }

  public int number_of_faces() {
    return CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_number_of_faces(swigCPtr, this);
  }

  public Weighted_alpha_shape_2_Face_handle infinite_face() {
    return new Weighted_alpha_shape_2_Face_handle(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_infinite_face__SWIG_0(swigCPtr, this), true);
  }

  public void infinite_face(Weighted_alpha_shape_2_Face_handle ref) {
    CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_infinite_face__SWIG_1(swigCPtr, this, Weighted_alpha_shape_2_Face_handle.getCPtr(ref), ref);
  }

  public Weighted_alpha_shape_2_Vertex_handle infinite_vertex() {
    return new Weighted_alpha_shape_2_Vertex_handle(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_infinite_vertex__SWIG_0(swigCPtr, this), true);
  }

  public void infinite_vertex(Weighted_alpha_shape_2_Vertex_handle ref) {
    CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_infinite_vertex__SWIG_1(swigCPtr, this, Weighted_alpha_shape_2_Vertex_handle.getCPtr(ref), ref);
  }

  public Weighted_alpha_shape_2_Vertex_handle finite_vertex() {
    return new Weighted_alpha_shape_2_Vertex_handle(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_finite_vertex__SWIG_0(swigCPtr, this), true);
  }

  public void finite_vertex(Weighted_alpha_shape_2_Vertex_handle ref) {
    CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_finite_vertex__SWIG_1(swigCPtr, this, Weighted_alpha_shape_2_Vertex_handle.getCPtr(ref), ref);
  }

  public boolean is_infinite(Weighted_alpha_shape_2_Vertex_handle c) {
    return CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_is_infinite__SWIG_0(swigCPtr, this, Weighted_alpha_shape_2_Vertex_handle.getCPtr(c), c);
  }

  public boolean is_infinite(Weighted_alpha_shape_2_Face_handle c) {
    return CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_is_infinite__SWIG_1(swigCPtr, this, Weighted_alpha_shape_2_Face_handle.getCPtr(c), c);
  }

  public boolean is_infinite(Weighted_alpha_shape_2_Face_handle c1, int c2) {
    return CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_is_infinite__SWIG_2(swigCPtr, this, Weighted_alpha_shape_2_Face_handle.getCPtr(c1), c1, c2);
  }

  public boolean is_edge(Weighted_alpha_shape_2_Vertex_handle c1, Weighted_alpha_shape_2_Vertex_handle c2) {
    return CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_is_edge__SWIG_0(swigCPtr, this, Weighted_alpha_shape_2_Vertex_handle.getCPtr(c1), c1, Weighted_alpha_shape_2_Vertex_handle.getCPtr(c2), c2);
  }

  public boolean is_face(Weighted_alpha_shape_2_Vertex_handle c1, Weighted_alpha_shape_2_Vertex_handle c2, Weighted_alpha_shape_2_Vertex_handle c3) {
    return CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_is_face__SWIG_0(swigCPtr, this, Weighted_alpha_shape_2_Vertex_handle.getCPtr(c1), c1, Weighted_alpha_shape_2_Vertex_handle.getCPtr(c2), c2, Weighted_alpha_shape_2_Vertex_handle.getCPtr(c3), c3);
  }

  public boolean is_infinite(Weighted_alpha_shape_2_Edge c) {
    return CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_is_infinite__SWIG_3(swigCPtr, this, Weighted_alpha_shape_2_Edge.getCPtr(c), c);
  }

  public boolean is_edge(Weighted_alpha_shape_2_Vertex_handle va, Weighted_alpha_shape_2_Vertex_handle vb, Ref_Weighted_alpha_shape_2_Face_handle fr, Ref_int i) {
    return CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_is_edge__SWIG_1(swigCPtr, this, Weighted_alpha_shape_2_Vertex_handle.getCPtr(va), va, Weighted_alpha_shape_2_Vertex_handle.getCPtr(vb), vb, Ref_Weighted_alpha_shape_2_Face_handle.getCPtr(fr), fr, Ref_int.getCPtr(i), i);
  }

  public boolean includes_edge(Weighted_alpha_shape_2_Vertex_handle va, Weighted_alpha_shape_2_Vertex_handle vb, Ref_Weighted_alpha_shape_2_Vertex_handle vbr, Ref_Weighted_alpha_shape_2_Face_handle fr, Ref_int i) {
    return CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_includes_edge(swigCPtr, this, Weighted_alpha_shape_2_Vertex_handle.getCPtr(va), va, Weighted_alpha_shape_2_Vertex_handle.getCPtr(vb), vb, Ref_Weighted_alpha_shape_2_Vertex_handle.getCPtr(vbr), vbr, Ref_Weighted_alpha_shape_2_Face_handle.getCPtr(fr), fr, Ref_int.getCPtr(i), i);
  }

  public boolean is_face(Weighted_alpha_shape_2_Vertex_handle v1, Weighted_alpha_shape_2_Vertex_handle v2, Weighted_alpha_shape_2_Vertex_handle v3, Ref_Weighted_alpha_shape_2_Face_handle fr) {
    return CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_is_face__SWIG_1(swigCPtr, this, Weighted_alpha_shape_2_Vertex_handle.getCPtr(v1), v1, Weighted_alpha_shape_2_Vertex_handle.getCPtr(v2), v2, Weighted_alpha_shape_2_Vertex_handle.getCPtr(v3), v3, Ref_Weighted_alpha_shape_2_Face_handle.getCPtr(fr), fr);
  }

  public Weighted_alpha_shape_2_Face_handle locate(Weighted_point_2 c) {
    return new Weighted_alpha_shape_2_Face_handle(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_locate__SWIG_0(swigCPtr, this, Weighted_point_2.getCPtr(c), c), true);
  }

  public Weighted_alpha_shape_2_Face_handle locate(Weighted_point_2 c1, Weighted_alpha_shape_2_Face_handle c2) {
    return new Weighted_alpha_shape_2_Face_handle(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_locate__SWIG_1(swigCPtr, this, Weighted_point_2.getCPtr(c1), c1, Weighted_alpha_shape_2_Face_handle.getCPtr(c2), c2), true);
  }

  public void locate(Weighted_point_2 c1, Weighted_alpha_shape_2_Face_handle c2, Weighted_alpha_shape_2_Face_handle ret) {
    CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_locate__SWIG_2(swigCPtr, this, Weighted_point_2.getCPtr(c1), c1, Weighted_alpha_shape_2_Face_handle.getCPtr(c2), c2, Weighted_alpha_shape_2_Face_handle.getCPtr(ret), ret);
  }

  public Oriented_side oriented_side(Weighted_alpha_shape_2_Face_handle c1, Weighted_point_2 c2) {
    return Oriented_side.swigToEnum(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_oriented_side(swigCPtr, this, Weighted_alpha_shape_2_Face_handle.getCPtr(c1), c1, Weighted_point_2.getCPtr(c2), c2));
  }

  public Oriented_side side_of_oriented_circle(Weighted_alpha_shape_2_Face_handle c1, Weighted_point_2 c2) {
    return Oriented_side.swigToEnum(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_side_of_oriented_circle(swigCPtr, this, Weighted_alpha_shape_2_Face_handle.getCPtr(c1), c1, Weighted_point_2.getCPtr(c2), c2));
  }

  public Weighted_alpha_shape_2_Face_handle locate(Weighted_point_2 query, Ref_Locate_type_2 lt, Ref_int li, Weighted_alpha_shape_2_Face_handle hint) {
    return new Weighted_alpha_shape_2_Face_handle(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_locate__SWIG_3(swigCPtr, this, Weighted_point_2.getCPtr(query), query, Ref_Locate_type_2.getCPtr(lt), lt, Ref_int.getCPtr(li), li, Weighted_alpha_shape_2_Face_handle.getCPtr(hint), hint), true);
  }

  public Weighted_alpha_shape_2_Face_handle locate(Weighted_point_2 query, Ref_Locate_type_2 lt, Ref_int li) {
    return new Weighted_alpha_shape_2_Face_handle(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_locate__SWIG_4(swigCPtr, this, Weighted_point_2.getCPtr(query), query, Ref_Locate_type_2.getCPtr(lt), lt, Ref_int.getCPtr(li), li), true);
  }

  public Weighted_alpha_shape_2_Finite_vertices_iterator finite_vertices() {
    return new Weighted_alpha_shape_2_Finite_vertices_iterator(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_finite_vertices(swigCPtr, this), true);
  }

  public Weighted_alpha_shape_2_Finite_edges_iterator finite_edges() {
    return new Weighted_alpha_shape_2_Finite_edges_iterator(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_finite_edges(swigCPtr, this), true);
  }

  public Weighted_alpha_shape_2_Finite_faces_iterator finite_faces() {
    return new Weighted_alpha_shape_2_Finite_faces_iterator(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_finite_faces(swigCPtr, this), true);
  }

  public Weighted_alpha_shape_2_All_vertices_iterator all_vertices() {
    return new Weighted_alpha_shape_2_All_vertices_iterator(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_all_vertices(swigCPtr, this), true);
  }

  public Weighted_alpha_shape_2_All_edges_iterator all_edges() {
    return new Weighted_alpha_shape_2_All_edges_iterator(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_all_edges(swigCPtr, this), true);
  }

  public Weighted_alpha_shape_2_All_faces_iterator all_faces() {
    return new Weighted_alpha_shape_2_All_faces_iterator(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_all_faces(swigCPtr, this), true);
  }

  public Weighted_alpha_shape_2_Point_iterator points() {
    return new Weighted_alpha_shape_2_Point_iterator(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_points(swigCPtr, this), true);
  }

  public Weighted_alpha_shape_2_Line_face_circulator line_walk(Weighted_point_2 p, Weighted_point_2 q) {
    return new Weighted_alpha_shape_2_Line_face_circulator(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_line_walk__SWIG_0(swigCPtr, this, Weighted_point_2.getCPtr(p), p, Weighted_point_2.getCPtr(q), q), true);
  }

  public Weighted_alpha_shape_2_Line_face_circulator line_walk(Weighted_point_2 p, Weighted_point_2 q, Weighted_alpha_shape_2_Face_handle f) {
    return new Weighted_alpha_shape_2_Line_face_circulator(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_line_walk__SWIG_1(swigCPtr, this, Weighted_point_2.getCPtr(p), p, Weighted_point_2.getCPtr(q), q, Weighted_alpha_shape_2_Face_handle.getCPtr(f), f), true);
  }

  public Weighted_alpha_shape_2_Face_circulator incident_faces(Weighted_alpha_shape_2_Vertex_handle c) {
    return new Weighted_alpha_shape_2_Face_circulator(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_incident_faces__SWIG_0(swigCPtr, this, Weighted_alpha_shape_2_Vertex_handle.getCPtr(c), c), true);
  }

  public void incident_faces(Weighted_alpha_shape_2_Vertex_handle c, Weighted_alpha_shape_2_Face_circulator ret) {
    CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_incident_faces__SWIG_1(swigCPtr, this, Weighted_alpha_shape_2_Vertex_handle.getCPtr(c), c, Weighted_alpha_shape_2_Face_circulator.getCPtr(ret), ret);
  }

  public Weighted_alpha_shape_2_Face_circulator incident_faces(Weighted_alpha_shape_2_Vertex_handle c1, Weighted_alpha_shape_2_Face_handle c2) {
    return new Weighted_alpha_shape_2_Face_circulator(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_incident_faces__SWIG_2(swigCPtr, this, Weighted_alpha_shape_2_Vertex_handle.getCPtr(c1), c1, Weighted_alpha_shape_2_Face_handle.getCPtr(c2), c2), true);
  }

  public void incident_faces(Weighted_alpha_shape_2_Vertex_handle c1, Weighted_alpha_shape_2_Face_handle c2, Weighted_alpha_shape_2_Face_circulator ret) {
    CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_incident_faces__SWIG_3(swigCPtr, this, Weighted_alpha_shape_2_Vertex_handle.getCPtr(c1), c1, Weighted_alpha_shape_2_Face_handle.getCPtr(c2), c2, Weighted_alpha_shape_2_Face_circulator.getCPtr(ret), ret);
  }

  public Weighted_alpha_shape_2_Edge_circulator incident_edges(Weighted_alpha_shape_2_Vertex_handle c) {
    return new Weighted_alpha_shape_2_Edge_circulator(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_incident_edges__SWIG_0(swigCPtr, this, Weighted_alpha_shape_2_Vertex_handle.getCPtr(c), c), true);
  }

  public void incident_edges(Weighted_alpha_shape_2_Vertex_handle c, Weighted_alpha_shape_2_Edge_circulator ret) {
    CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_incident_edges__SWIG_1(swigCPtr, this, Weighted_alpha_shape_2_Vertex_handle.getCPtr(c), c, Weighted_alpha_shape_2_Edge_circulator.getCPtr(ret), ret);
  }

  public Weighted_alpha_shape_2_Edge_circulator incident_edges(Weighted_alpha_shape_2_Vertex_handle c1, Weighted_alpha_shape_2_Face_handle c2) {
    return new Weighted_alpha_shape_2_Edge_circulator(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_incident_edges__SWIG_2(swigCPtr, this, Weighted_alpha_shape_2_Vertex_handle.getCPtr(c1), c1, Weighted_alpha_shape_2_Face_handle.getCPtr(c2), c2), true);
  }

  public void incident_edges(Weighted_alpha_shape_2_Vertex_handle c1, Weighted_alpha_shape_2_Face_handle c2, Weighted_alpha_shape_2_Edge_circulator ret) {
    CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_incident_edges__SWIG_3(swigCPtr, this, Weighted_alpha_shape_2_Vertex_handle.getCPtr(c1), c1, Weighted_alpha_shape_2_Face_handle.getCPtr(c2), c2, Weighted_alpha_shape_2_Edge_circulator.getCPtr(ret), ret);
  }

  public Weighted_alpha_shape_2_Vertex_circulator incident_vertices(Weighted_alpha_shape_2_Vertex_handle c) {
    return new Weighted_alpha_shape_2_Vertex_circulator(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_incident_vertices__SWIG_0(swigCPtr, this, Weighted_alpha_shape_2_Vertex_handle.getCPtr(c), c), true);
  }

  public void incident_vertices(Weighted_alpha_shape_2_Vertex_handle c, Weighted_alpha_shape_2_Vertex_circulator ret) {
    CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_incident_vertices__SWIG_1(swigCPtr, this, Weighted_alpha_shape_2_Vertex_handle.getCPtr(c), c, Weighted_alpha_shape_2_Vertex_circulator.getCPtr(ret), ret);
  }

  public Weighted_alpha_shape_2_Vertex_circulator incident_vertices(Weighted_alpha_shape_2_Vertex_handle c1, Weighted_alpha_shape_2_Face_handle c2) {
    return new Weighted_alpha_shape_2_Vertex_circulator(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_incident_vertices__SWIG_2(swigCPtr, this, Weighted_alpha_shape_2_Vertex_handle.getCPtr(c1), c1, Weighted_alpha_shape_2_Face_handle.getCPtr(c2), c2), true);
  }

  public void incident_vertices(Weighted_alpha_shape_2_Vertex_handle c1, Weighted_alpha_shape_2_Face_handle c2, Weighted_alpha_shape_2_Vertex_circulator ret) {
    CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_incident_vertices__SWIG_3(swigCPtr, this, Weighted_alpha_shape_2_Vertex_handle.getCPtr(c1), c1, Weighted_alpha_shape_2_Face_handle.getCPtr(c2), c2, Weighted_alpha_shape_2_Vertex_circulator.getCPtr(ret), ret);
  }

  public Weighted_alpha_shape_2_Vertex_handle mirror_vertex(Weighted_alpha_shape_2_Face_handle c1, int c2) {
    return new Weighted_alpha_shape_2_Vertex_handle(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_mirror_vertex__SWIG_0(swigCPtr, this, Weighted_alpha_shape_2_Face_handle.getCPtr(c1), c1, c2), true);
  }

  public void mirror_vertex(Weighted_alpha_shape_2_Face_handle c1, int c2, Weighted_alpha_shape_2_Vertex_handle ret) {
    CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_mirror_vertex__SWIG_1(swigCPtr, this, Weighted_alpha_shape_2_Face_handle.getCPtr(c1), c1, c2, Weighted_alpha_shape_2_Vertex_handle.getCPtr(ret), ret);
  }

  public int mirror_index(Weighted_alpha_shape_2_Face_handle c1, int c2) {
    return CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_mirror_index(swigCPtr, this, Weighted_alpha_shape_2_Face_handle.getCPtr(c1), c1, c2);
  }

  public int ccw(int c) {
    return CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_ccw(swigCPtr, this, c);
  }

  public int cw(int c) {
    return CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_cw(swigCPtr, this, c);
  }

  public Weighted_point_2 circumcenter(Weighted_alpha_shape_2_Face_handle c) {
    return new Weighted_point_2(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_circumcenter__SWIG_0(swigCPtr, this, Weighted_alpha_shape_2_Face_handle.getCPtr(c), c), true);
  }

  public void circumcenter(Weighted_alpha_shape_2_Face_handle c, Weighted_point_2 ret) {
    CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_circumcenter__SWIG_1(swigCPtr, this, Weighted_alpha_shape_2_Face_handle.getCPtr(c), c, Weighted_point_2.getCPtr(ret), ret);
  }

  public void set_infinite_vertex(Weighted_alpha_shape_2_Vertex_handle c) {
    CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_set_infinite_vertex(swigCPtr, this, Weighted_alpha_shape_2_Vertex_handle.getCPtr(c), c);
  }

  public boolean is_valid() {
    return CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_is_valid__SWIG_0(swigCPtr, this);
  }

  public boolean is_valid(boolean c) {
    return CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_is_valid__SWIG_1(swigCPtr, this, c);
  }

  public boolean is_valid(boolean c1, int c2) {
    return CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_is_valid__SWIG_2(swigCPtr, this, c1, c2);
  }

  public Triangle_2 triangle(Weighted_alpha_shape_2_Face_handle c) {
    return new Triangle_2(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_triangle__SWIG_0(swigCPtr, this, Weighted_alpha_shape_2_Face_handle.getCPtr(c), c), true);
  }

  public void triangle(Weighted_alpha_shape_2_Face_handle c, Triangle_2 ret) {
    CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_triangle__SWIG_1(swigCPtr, this, Weighted_alpha_shape_2_Face_handle.getCPtr(c), c, Triangle_2.getCPtr(ret), ret);
  }

  public Segment_2 segment(Weighted_alpha_shape_2_Face_handle c1, int c2) {
    return new Segment_2(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_segment__SWIG_0(swigCPtr, this, Weighted_alpha_shape_2_Face_handle.getCPtr(c1), c1, c2), true);
  }

  public void segment(Weighted_alpha_shape_2_Face_handle c1, int c2, Segment_2 ret) {
    CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_segment__SWIG_1(swigCPtr, this, Weighted_alpha_shape_2_Face_handle.getCPtr(c1), c1, c2, Segment_2.getCPtr(ret), ret);
  }

  public Segment_2 segment(Weighted_alpha_shape_2_Edge c) {
    return new Segment_2(CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_segment__SWIG_2(swigCPtr, this, Weighted_alpha_shape_2_Edge.getCPtr(c), c), true);
  }

  public void segment(Weighted_alpha_shape_2_Edge c, Segment_2 ret) {
    CGAL_Alpha_shape_2JNI.Internal_Triangulation_2_Internal_regular_Weighted_alpha_shape_2_segment__SWIG_3(swigCPtr, this, Weighted_alpha_shape_2_Edge.getCPtr(c), c, Segment_2.getCPtr(ret), ret);
  }

}
