/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Alpha_shape_2;

public class Vertex_range {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Vertex_range(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Vertex_range obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_Alpha_shape_2JNI.delete_Vertex_range(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Vertex_range() {
    this(CGAL_Alpha_shape_2JNI.new_Vertex_range__SWIG_0(), true);
  }

  public Vertex_range(double first, double second) {
    this(CGAL_Alpha_shape_2JNI.new_Vertex_range__SWIG_1(first, second), true);
  }

  public Vertex_range(Vertex_range p) {
    this(CGAL_Alpha_shape_2JNI.new_Vertex_range__SWIG_2(Vertex_range.getCPtr(p), p), true);
  }

  public void setFirst(double value) {
    CGAL_Alpha_shape_2JNI.Vertex_range_first_set(swigCPtr, this, value);
  }

  public double getFirst() {
    return CGAL_Alpha_shape_2JNI.Vertex_range_first_get(swigCPtr, this);
  }

  public void setSecond(double value) {
    CGAL_Alpha_shape_2JNI.Vertex_range_second_set(swigCPtr, this, value);
  }

  public double getSecond() {
    return CGAL_Alpha_shape_2JNI.Vertex_range_second_get(swigCPtr, this);
  }

}
