/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Alpha_shape_2;
import CGAL.Java.JavaData; 
public class Weighted_alpha_shape_2_Face_handle {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Weighted_alpha_shape_2_Face_handle(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Weighted_alpha_shape_2_Face_handle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_Alpha_shape_2JNI.delete_Weighted_alpha_shape_2_Face_handle(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Weighted_alpha_shape_2_Face_handle() {
    this(CGAL_Alpha_shape_2JNI.new_Weighted_alpha_shape_2_Face_handle(), true);
  }

  public int dimension() {
    return CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_dimension(swigCPtr, this);
  }

  public Weighted_alpha_shape_2_Vertex_handle vertex(int c) {
    return new Weighted_alpha_shape_2_Vertex_handle(CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_vertex__SWIG_0(swigCPtr, this, c), true);
  }

  public void vertex(int c, Weighted_alpha_shape_2_Vertex_handle ret) {
    CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_vertex__SWIG_1(swigCPtr, this, c, Weighted_alpha_shape_2_Vertex_handle.getCPtr(ret), ret);
  }

  public boolean has_vertex(Weighted_alpha_shape_2_Vertex_handle c) {
    return CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_has_vertex(swigCPtr, this, Weighted_alpha_shape_2_Vertex_handle.getCPtr(c), c);
  }

  public int index(Weighted_alpha_shape_2_Vertex_handle c) {
    return CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_index__SWIG_0(swigCPtr, this, Weighted_alpha_shape_2_Vertex_handle.getCPtr(c), c);
  }

  public Weighted_alpha_shape_2_Face_handle neighbor(int c) {
    return new Weighted_alpha_shape_2_Face_handle(CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_neighbor__SWIG_0(swigCPtr, this, c), true);
  }

  public void neighbor(int c, Weighted_alpha_shape_2_Face_handle ret) {
    CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_neighbor__SWIG_1(swigCPtr, this, c, Weighted_alpha_shape_2_Face_handle.getCPtr(ret), ret);
  }

  public boolean has_neighbor(Weighted_alpha_shape_2_Face_handle c) {
    return CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_has_neighbor(swigCPtr, this, Weighted_alpha_shape_2_Face_handle.getCPtr(c), c);
  }

  public int index(Weighted_alpha_shape_2_Face_handle c) {
    return CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_index__SWIG_1(swigCPtr, this, Weighted_alpha_shape_2_Face_handle.getCPtr(c), c);
  }

  public void set_vertex(int c1, Weighted_alpha_shape_2_Vertex_handle c2) {
    CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_set_vertex(swigCPtr, this, c1, Weighted_alpha_shape_2_Vertex_handle.getCPtr(c2), c2);
  }

  public void set_vertices() {
    CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_set_vertices__SWIG_0(swigCPtr, this);
  }

  public void set_vertices(Weighted_alpha_shape_2_Vertex_handle c1, Weighted_alpha_shape_2_Vertex_handle c2, Weighted_alpha_shape_2_Vertex_handle c3) {
    CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_set_vertices__SWIG_1(swigCPtr, this, Weighted_alpha_shape_2_Vertex_handle.getCPtr(c1), c1, Weighted_alpha_shape_2_Vertex_handle.getCPtr(c2), c2, Weighted_alpha_shape_2_Vertex_handle.getCPtr(c3), c3);
  }

  public void set_neighbor(int c1, Weighted_alpha_shape_2_Face_handle c2) {
    CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_set_neighbor(swigCPtr, this, c1, Weighted_alpha_shape_2_Face_handle.getCPtr(c2), c2);
  }

  public void set_neighbors() {
    CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_set_neighbors__SWIG_0(swigCPtr, this);
  }

  public void set_neighbors(Weighted_alpha_shape_2_Face_handle c1, Weighted_alpha_shape_2_Face_handle c2, Weighted_alpha_shape_2_Face_handle c3) {
    CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_set_neighbors__SWIG_1(swigCPtr, this, Weighted_alpha_shape_2_Face_handle.getCPtr(c1), c1, Weighted_alpha_shape_2_Face_handle.getCPtr(c2), c2, Weighted_alpha_shape_2_Face_handle.getCPtr(c3), c3);
  }

  public void reorient() {
    CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_reorient(swigCPtr, this);
  }

  public void ccw_permute() {
    CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_ccw_permute(swigCPtr, this);
  }

  public void cw_permute() {
    CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_cw_permute(swigCPtr, this);
  }

  public boolean is_valid() {
    return CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_is_valid__SWIG_0(swigCPtr, this);
  }

  public boolean is_valid(boolean c) {
    return CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_is_valid__SWIG_1(swigCPtr, this, c);
  }

  public boolean lt(Weighted_alpha_shape_2_Face_handle p) {
    return CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_lt(swigCPtr, this, Weighted_alpha_shape_2_Face_handle.getCPtr(p), p);
  }

  public boolean gt(Weighted_alpha_shape_2_Face_handle p) {
    return CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_gt(swigCPtr, this, Weighted_alpha_shape_2_Face_handle.getCPtr(p), p);
  }

  public boolean le(Weighted_alpha_shape_2_Face_handle p) {
    return CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_le(swigCPtr, this, Weighted_alpha_shape_2_Face_handle.getCPtr(p), p);
  }

  public boolean ge(Weighted_alpha_shape_2_Face_handle p) {
    return CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_ge(swigCPtr, this, Weighted_alpha_shape_2_Face_handle.getCPtr(p), p);
  }

  public boolean equals(Weighted_alpha_shape_2_Face_handle p) {
    return CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_equals(swigCPtr, this, Weighted_alpha_shape_2_Face_handle.getCPtr(p), p);
  }

  public boolean not_equals(Weighted_alpha_shape_2_Face_handle p) {
    return CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_not_equals(swigCPtr, this, Weighted_alpha_shape_2_Face_handle.getCPtr(p), p);
  }

  public int hashCode() {
    return CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_hashCode(swigCPtr, this);
  }

  public Weighted_alpha_shape_2_Face_handle clone() {
    return new Weighted_alpha_shape_2_Face_handle(CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_clone__SWIG_0(swigCPtr, this), true);
  }

  public void clone(Weighted_alpha_shape_2_Face_handle other) {
    CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_clone__SWIG_1(swigCPtr, this, Weighted_alpha_shape_2_Face_handle.getCPtr(other), other);
  }

  public JavaData info() {
    return new JavaData(CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_info(swigCPtr, this), false);
  }

  public void get_info(JavaData jd) {
    CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_get_info(swigCPtr, this, JavaData.getCPtr(jd), jd);
  }

  public void set_info(JavaData jd) {
    CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_set_info(swigCPtr, this, JavaData.getCPtr(jd), jd);
  }

  public double get_alpha() {
    return CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_get_alpha(swigCPtr, this);
  }

  public Face_Interval_3 get_ranges(int i) {
    return new Face_Interval_3(CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_get_ranges(swigCPtr, this, i), true);
  }

  public void set_ranges(int i, Face_Interval_3 r) {
    CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_set_ranges(swigCPtr, this, i, Face_Interval_3.getCPtr(r), r);
  }

  public void set_alpha(double d) {
    CGAL_Alpha_shape_2JNI.Weighted_alpha_shape_2_Face_handle_set_alpha(swigCPtr, this, d);
  }

}
