This is makeindex, version 2.15 [TeX Live 2015/W32TeX] (kpathsea + Thai support).
Scanning style file ./Tesi_Magistrale_Manuela_Ruocco.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Tesi_Magistrale_Manuela_Ruocco.acn....done (71 entries accepted, 0 rejected).
Sorting entries....done (465 comparisons).
Generating output file Tesi_Magistrale_Manuela_Ruocco.acr....done (81 lines written, 0 warnings).
Output written in Tesi_Magistrale_Manuela_Ruocco.acr.
Transcript written in Tesi_Magistrale_Manuela_Ruocco.alg.
