/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Interpolation;
import CGAL.Kernel.Point_2; import CGAL.Kernel.Vector_2;
public class Data_access_vector_2 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Data_access_vector_2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Data_access_vector_2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_InterpolationJNI.delete_Data_access_vector_2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Data_access_vector_2() {
    this(CGAL_InterpolationJNI.new_Data_access_vector_2(), true);
  }

  public void set(Point_2 p, Vector_2 value) {
    CGAL_InterpolationJNI.Data_access_vector_2_set(swigCPtr, this, Point_2.getCPtr(p), p, Vector_2.getCPtr(value), value);
  }

  public Vector_2 get(Point_2 p) {
    return new Vector_2(CGAL_InterpolationJNI.Data_access_vector_2_get(swigCPtr, this, Point_2.getCPtr(p), p), true);
  }

}
