clc; close all; clear all;

%% Import data
Delta2Slottedtc0p12 = importdata('Delta2Slottedtc0p12.mat');
Delta2Slottedtc0p21 = importdata('Delta2Slottedtc0p21.mat');
Delta2Slottedtc0p30 = importdata('Delta2Slottedtc0p30.mat');

nPoints = 50;
deltaF_Vector = transpose(linspace(0, 100, nPoints));

%% t/c = 0.12
smoothingParameter = 0.999999;
Delta2Slottedtc0p12_SplineStatic_alphaDelta0p1 = csaps( ...
    Delta2Slottedtc0p12(:,1), ...
    Delta2Slottedtc0p12(:,2), ...
    smoothingParameter ...
    );

Delta2Slottedtc0p12_Static_alphaDelta0p1 = ppval( ...
    Delta2Slottedtc0p12_SplineStatic_alphaDelta0p1, ...
    deltaF_Vector ...
    );

%% t/c = 0.21
smoothingParameter = 0.999999;
Delta2Slottedtc0p21_SplineStatic_alphaDelta0p2 = csaps( ...
    Delta2Slottedtc0p21(:,1), ...
    Delta2Slottedtc0p21(:,2), ...
    smoothingParameter ...
    );

Delta2Slottedtc0p21_Static_alphaDelta0p2 = ppval( ...
    Delta2Slottedtc0p21_SplineStatic_alphaDelta0p2, ...
    deltaF_Vector ...
    );

%% t/c = 0.3
smoothingParameter = 0.999999;
Delta2Slottedtc0p30_SplineStatic_alphaDelta0p3 = csaps( ...
    Delta2Slottedtc0p30(:,1), ...
    Delta2Slottedtc0p30(:,2), ...
    smoothingParameter ...
    );

Delta2Slottedtc0p30_Static_alphaDelta0p3 = ppval( ...
    Delta2Slottedtc0p30_SplineStatic_alphaDelta0p3, ...
    deltaF_Vector ...
    );

%% Plots
figure(1)
plot ( ...
    deltaF_Vector, Delta2Slottedtc0p12_Static_alphaDelta0p1, 'b-+' ... , ...
 );
 hold on
 
 plot ( ...
    deltaF_Vector, Delta2Slottedtc0p21_Static_alphaDelta0p2, 'b-o' ... , ...
 );

hold on

plot ( ...
    deltaF_Vector, Delta2Slottedtc0p30_Static_alphaDelta0p3, 'b-*' ... , ...
 );

 xlabel('c_f/c'); ylabel('\delta_1');
 title('\delta_2 variation with \delta_f for Slotted flap');
  legend('t/c = 0.12', 't/c = 0.21', 't/c = 0.30');
 axis([0 100 0 0.2]);
 grid on;
 %% preparing output to HDF

% t/c
tcVector = [ ...
    0.12;0.21;0.30 ...
    ];

%columns --> curves
myData = [ ...
    Delta2Slottedtc0p12_Static_alphaDelta0p1,...
    Delta2Slottedtc0p21_Static_alphaDelta0p2, ... 
    Delta2Slottedtc0p30_Static_alphaDelta0p3, ... 
    ];    
hdfFileName = 'Delta2_vs_delta_flap_Slotted.h5';

if ( exist(hdfFileName, 'file') )
    fprintf('file %s exists, deleting and creating a new one\n', hdfFileName);
    delete(hdfFileName)
else
    fprintf('Creating new file %s\n', hdfFileName);
end

% Dataset: data
h5create(hdfFileName, '/Delta2_vs_delta_flap_Slotted/data', size(myData'));
h5write(hdfFileName, '/Delta2_vs_delta_flap_Slotted/data', myData');

% Dataset: var_0
h5create(hdfFileName, '/Delta2_vs_delta_flap_Slotted/var_0', size(tcVector'));
h5write(hdfFileName, '/Delta2_vs_delta_flap_Slotted/var_0', tcVector');

% Dataset: var_1
h5create(hdfFileName, '/Delta2_vs_delta_flap_Slotted/var_1', size(deltaF_Vector'));
h5write(hdfFileName, '/Delta2_vs_delta_flap_Slotted/var_1', deltaF_Vector');