clc; close all; clear all;

%% Import data
Delta3taper0 = importdata('Delta3taper0.mat');
Delta3taper0p166 = importdata('Delta3taper0p166.mat');
Delta3taper0p25 = importdata('Delta3taper0p25.mat');
Delta3taper0p33 = importdata('Delta3taper0p33.mat');
Delta3taper0p5 = importdata('Delta3taper0p5.mat');
Delta3taper1 = importdata('Delta3taper1.mat');

nPoints = 50;
bf_b_Vector = transpose(linspace(0, 1, nPoints));

%% taper ratio = 0
smoothingParameter = 0.999999;
Delta3taper0_SplineStatic_alphaDelta0p1 = csaps( ...
    Delta3taper0(:,1), ...
    Delta3taper0(:,2), ...
    smoothingParameter ...
    );

Delta3taper0_Static_alphaDelta0p1 = ppval( ...
    Delta3taper0_SplineStatic_alphaDelta0p1, ...
    bf_b_Vector ...
    );

%% taper ratio = 0.166
smoothingParameter = 0.999999;
Delta3taper0p166_SplineStatic_alphaDelta0p2 = csaps( ...
    Delta3taper0p166(:,1), ...
    Delta3taper0p166(:,2), ...
    smoothingParameter ...
    );

Delta3taper0p166_Static_alphaDelta0p2 = ppval( ...
    Delta3taper0p166_SplineStatic_alphaDelta0p2, ...
    bf_b_Vector ...
    );

%% taper ratio = 0.25
smoothingParameter = 0.999999;
Delta3taper0p25_SplineStatic_alphaDelta0p3 = csaps( ...
    Delta3taper0p25(:,1), ...
    Delta3taper0p25(:,2), ...
    smoothingParameter ...
    );

Delta3taper0p25_Static_alphaDelta0p3 = ppval( ...
    Delta3taper0p25_SplineStatic_alphaDelta0p3, ...
    bf_b_Vector ...
    );

%% taper ratio = 0.33
smoothingParameter = 0.999999;
Delta3taper0p33_SplineStatic_alphaDelta0p4 = csaps( ...
    Delta3taper0p33(:,1), ...
    Delta3taper0p33(:,2), ...
    smoothingParameter ...
    );

Delta3taper0p33_Static_alphaDelta0p4 = ppval( ...
    Delta3taper0p33_SplineStatic_alphaDelta0p4, ...
    bf_b_Vector ...
    );

%% taper ratio = 0.5
smoothingParameter = 0.999999;
Delta3taper0p5_SplineStatic_alphaDelta0p5 = csaps( ...
    Delta3taper0p5(:,1), ...
    Delta3taper0p5(:,2), ...
    smoothingParameter ...
    );

Delta3taper0p5_Static_alphaDelta0p5 = ppval( ...
    Delta3taper0p5_SplineStatic_alphaDelta0p5, ...
    bf_b_Vector ...
    );

%% taper ratio = 1
smoothingParameter = 0.999999;
Delta3taper1_SplineStatic_alphaDelta0p6 = csaps( ...
    Delta3taper1(:,1), ...
    Delta3taper1(:,2), ...
    smoothingParameter ...
    );

Delta3taper1_Static_alphaDelta0p6 = ppval( ...
    Delta3taper1_SplineStatic_alphaDelta0p6, ...
    bf_b_Vector ...
    );

%% Plots
figure(1)
plot ( ...
    bf_b_Vector, Delta3taper0_Static_alphaDelta0p1, 'b-+' ... , ...
 );
 hold on
 
 plot ( ...
    bf_b_Vector, Delta3taper0p166_Static_alphaDelta0p2, 'b-o' ... , ...
 );

hold on

plot ( ...
    bf_b_Vector, Delta3taper0p25_Static_alphaDelta0p3, 'b-*' ... , ...
 );

hold on

plot ( ...
    bf_b_Vector, Delta3taper0p33_Static_alphaDelta0p4, 'b-.' ... , ...
 );

hold on

plot ( ...
    bf_b_Vector, Delta3taper0p5_Static_alphaDelta0p5, 'b-x' ... , ...
 );

hold on

plot ( ...
    bf_b_Vector, Delta3taper1_Static_alphaDelta0p6, 'b-^' ... , ...
 );

 xlabel('b_f/b'); ylabel('\delta_3');
 title('\delta_3 coefficient variation with b_f/b');
  legend('taper ratio = 0','taper ratio = 0.166','taper ratio = 0.25', ...
         'taper ratio = 0.33','taper ratio = 0.5','taper ratio = 1');
 axis([0 1 0 1]);
 grid on;
 %% preparing output to HDF

% taper ratio
taperRatio_Vector = [ ...
    0;0.166;0.25;0.33;0.5;1 ...
    ];

%columns --> curves
myData = [ ...
    Delta3taper0_Static_alphaDelta0p1,...
        Delta3taper0p166_Static_alphaDelta0p2, ... 
        Delta3taper0p25_Static_alphaDelta0p3, ... 
        Delta3taper0p33_Static_alphaDelta0p4, ...
        Delta3taper0p5_Static_alphaDelta0p5, ...
        Delta3taper1_Static_alphaDelta0p6, ...
        ];    
hdfFileName = 'Delta3_vs_bf_b.h5';

if ( exist(hdfFileName, 'file') )
    fprintf('file %s exists, deleting and creating a new one\n', hdfFileName);
    delete(hdfFileName)
else
    fprintf('Creating new file %s\n', hdfFileName);
end

% Dataset: data
h5create(hdfFileName, '/Delta3_vs_bf_b/data', size(myData'));
h5write(hdfFileName, '/Delta3_vs_bf_b/data', myData');

% Dataset: var_0
h5create(hdfFileName, '/Delta3_vs_bf_b/var_0', size(taperRatio_Vector'));
h5write(hdfFileName, '/Delta3_vs_bf_b/var_0', taperRatio_Vector');

% Dataset: var_1
h5create(hdfFileName, '/Delta3_vs_bf_b/var_1', size(bf_b_Vector'));
h5write(hdfFileName, '/Delta3_vs_bf_b/var_1', bf_b_Vector');