clc; close all; clear all;

%% Import data
EtaDeltaPlainCfC0p1 = importdata('EtaDeltaPlainCfC0p1.mat');
EtaDeltaPlainCfC0p2 = importdata('EtaDeltaPlainCfC0p2.mat');
EtaDeltaPlainCfC0p3 = importdata('EtaDeltaPlainCfC0p3.mat');
EtaDeltaPlainCfC0p4 = importdata('EtaDeltaPlainCfC0p4.mat');

nPoints = 50;
deltafVector = transpose(linspace(0, 60, nPoints));

%% Cf_C = 0.1
smoothingParameter = 0.999999;
EtaDeltaPlainCfC0p1_SplineStatic = csaps( ...
    EtaDeltaPlainCfC0p1(:,1), ...
    EtaDeltaPlainCfC0p1(:,2), ...
    smoothingParameter ...
    );

EtaDeltaPlainCfC0p1_Static = ppval( ...
    EtaDeltaPlainCfC0p1_SplineStatic, ...
    deltafVector ...
    );

%% Cf_C = 0.2  
smoothingParameter = 0.999999;
EtaDeltaPlainCfC0p2_SplineStatic = csaps( ...
    EtaDeltaPlainCfC0p2(:,1), ...
    EtaDeltaPlainCfC0p2(:,2), ...
    smoothingParameter ...
    );

EtaDeltaPlainCfC0p2_Static = ppval( ...
    EtaDeltaPlainCfC0p2_SplineStatic, ...
    deltafVector ...
    );

%% Cf_C = 0.3 
smoothingParameter = 0.999999;
EtaDeltaPlainCfC0p3_SplineStatic = csaps( ...
    EtaDeltaPlainCfC0p3(:,1), ...
    EtaDeltaPlainCfC0p3(:,2), ...
    smoothingParameter ...
    );

EtaDeltaPlainCfC0p3_Static = ppval( ...
    EtaDeltaPlainCfC0p3_SplineStatic, ...
    deltafVector ...
    );

%% Cf_C = 0.4 
smoothingParameter = 0.999999;
EtaDeltaPlainCfC0p4_SplineStatic = csaps( ...
    EtaDeltaPlainCfC0p4(:,1), ...
    EtaDeltaPlainCfC0p4(:,2), ...
    smoothingParameter ...
    );

EtaDeltaPlainCfC0p4_Static = ppval( ...
    EtaDeltaPlainCfC0p4_SplineStatic, ...
    deltafVector ...
    );

%% Plots
figure(1)

plot ( ...
    deltafVector, EtaDeltaPlainCfC0p1_Static, 'b-*' ... , ...
 );

hold on;

plot ( ...
    deltafVector, EtaDeltaPlainCfC0p2_Static, 'b-+' ... , ...
 );

hold on;

plot ( ...
    deltafVector, EtaDeltaPlainCfC0p3_Static, 'b-^' ... , ...
 );

hold on;

plot ( ...
    deltafVector, EtaDeltaPlainCfC0p4_Static, 'b-' ... , ...
 );

xlabel('\delta_f'); ylabel('\eta_\delta');
 title('\eta_\delta variation with \delta_f parameterized in c_f/c');
 legend('c_f/c = 0.1', 'c_f/c = 0.2', 'c_f/c = 0.3', 'c_f/c = 0.4');
 
 axis([0 60 0.3 1]);
 grid on;
 %% preparing output to HDF
 
% FlapType (see number for each section)
flapTypeVector = [ ...
    1;2;3;4 ...
    ]; 
 
%columns --> curves
myData = [ ...
    EtaDeltaPlainCfC0p1_Static, ...
    EtaDeltaPlainCfC0p2_Static, ...
    EtaDeltaPlainCfC0p3_Static, ...
    EtaDeltaPlainCfC0p4_Static
    ];    
hdfFileName = 'EtaDelta_vs_DeltaFlap_Plain.h5';

if ( exist(hdfFileName, 'file') )
    fprintf('file %s exists, deleting and creating a new one\n', hdfFileName);
    delete(hdfFileName)
else
    fprintf('Creating new file %s\n', hdfFileName);
end

% Dataset: data
h5create(hdfFileName, '/EtaDelta_vs_DeltaFlap_Plain/data', size(myData'));
h5write(hdfFileName, '/EtaDelta_vs_DeltaFlap_Plain/data', myData');

% Dataset: var_0
h5create(hdfFileName, '/EtaDelta_vs_DeltaFlap_Plain/var_0', size(flapTypeVector'));
h5write(hdfFileName, '/EtaDelta_vs_DeltaFlap_Plain/var_0', flapTypeVector');

% Dataset: var_1
h5create(hdfFileName, '/EtaDelta_vs_DeltaFlap_Plain/var_1', size(deltafVector'));
h5write(hdfFileName, '/EtaDelta_vs_DeltaFlap_Plain/var_1', deltafVector');