clc; close all; clear all;

%% Import data
K1_1slot = importdata('K1splitplain1slot.mat');
K1_2slot = importdata('K12slotFowler.mat');
K1plain = importdata('K1splitplain1slot.mat');
K1fowler = importdata('K12slotFowler.mat');
K1_3slot = importdata('K12slotFowler.mat');

nPoints = 50;
Cf_c_Vector = transpose(linspace(0, 24, nPoints));

%% 1-Slot  (1)
smoothingParameter = 0.999999;
K1_1slot_SplineStatic = csaps( ...
    K1_1slot(:,1), ...
    K1_1slot(:,2), ...
    smoothingParameter ...
    );

K1_1slot_Static = ppval( ...
    K1_1slot_SplineStatic, ...
    Cf_c_Vector ...
    );

%% 2-Slot  (2)
smoothingParameter = 0.999999;
K1_2slot_SplineStatic = csaps( ...
    K1_2slot(:,1), ...
    K1_2slot(:,2), ...
    smoothingParameter ...
    );

K1_2slot_Static = ppval( ...
    K1_2slot_SplineStatic, ...
    Cf_c_Vector ...
    );

%% Plain  (4)
smoothingParameter = 0.999999;
K1plain_SplineStatic = csaps( ...
    K1plain(:,1), ...
    K1plain(:,2), ...
    smoothingParameter ...
    );

K1plain_Static = ppval( ...
    K1plain_SplineStatic, ...
    Cf_c_Vector ...
    );

%% Fowler  (5)
smoothingParameter = 0.999999;
K1fowler_SplineStatic = csaps( ...
    K1fowler(:,1), ...
    K1fowler(:,2), ...
    smoothingParameter ...
    );

K1fowler_Static = ppval( ...
    K1fowler_SplineStatic, ...
    Cf_c_Vector ...
    );

%% 3-Slot  (5)
smoothingParameter = 0.999999;
K1_3slot_SplineStatic = csaps( ...
    K1_3slot(:,1), ...
    K1_3slot(:,2), ...
    smoothingParameter ...
    );

K1_3slot_Static = ppval( ...
    K1_3slot_SplineStatic, ...
    Cf_c_Vector ...
    );

%% Plots
figure(1)

plot ( ...
    Cf_c_Vector, K1_1slot_Static, 'b-*' ... , ...
 );

hold on;

plot ( ...
    Cf_c_Vector, K1_2slot_Static, 'b-+' ... , ...
 );

hold on;

plot ( ...
    Cf_c_Vector, K1plain_Static, 'b-.' ... , ...
 );

hold on;

plot ( ...
    Cf_c_Vector, K1fowler_Static, 'b-^' ... , ...
 );

hold on;

plot ( ...
    Cf_c_Vector, K1_3slot_Static, 'b' ... , ...
 );

xlabel('c_f/c (%)'); ylabel('K1');
 title('K1 coefficient variation with flap chord ratio');
 legend('1-Slot', '2-Slot', 'Plain Flap', 'Fowler', '3-Slot');
 
 axis([0 24 0 1.2]);
 grid on;
 %% preparing output to HDF
 
% FlapType (see number for each section)
flapTypeVector = [ ...
    1;2;3;4;5 ...
    ]; 
 
%columns --> curves
myData = [ ...
    K1_1slot_Static, ...
    K1_2slot_Static, ...
    K1plain_Static, ...
    K1fowler_Static, ...
    K1_3slot_Static
    ];    
hdfFileName = 'K1_vs_FlapChordRatio.h5';

if ( exist(hdfFileName, 'file') )
    fprintf('file %s exists, deleting and creating a new one\n', hdfFileName);
    delete(hdfFileName)
else
    fprintf('Creating new file %s\n', hdfFileName);
end

% Dataset: data
h5create(hdfFileName, '/K1_vs_FlapChordRatio/data', size(myData'));
h5write(hdfFileName, '/K1_vs_FlapChordRatio/data', myData');

% Dataset: var_0
h5create(hdfFileName, '/K1_vs_FlapChordRatio/var_0', size(flapTypeVector'));
h5write(hdfFileName, '/K1_vs_FlapChordRatio/var_0', flapTypeVector');

% Dataset: var_1
h5create(hdfFileName, '/K1_vs_FlapChordRatio/var_1', size(Cf_c_Vector'));
h5write(hdfFileName, '/K1_vs_FlapChordRatio/var_1', Cf_c_Vector');