clc; close all; clear all;

%% Import data
K2_1slot = importdata('K21slot.mat');
K2_2slot = importdata('K22slot.mat');
K2plain = importdata('K2splitplain.mat');
K2Fowler = importdata('K2Fowler.mat');
K2_3slot = importdata('K22slot.mat');

nPoints = 50;
deltafVector = transpose(linspace(0, 60, nPoints));

%% 1-Slot (1)
smoothingParameter = 0.999999;
K2_1slot_SplineStatic = csaps( ...
    K2_1slot(:,1), ...
    K2_1slot(:,2), ...
    smoothingParameter ...
    );

K2_1slot_Static = ppval( ...
    K2_1slot_SplineStatic, ...
    deltafVector ...
    );

%% 2-Slot  (2)
smoothingParameter = 0.999999;
K2_2slot_SplineStatic = csaps( ...
    K2_2slot(:,1), ...
    K2_2slot(:,2), ...
    smoothingParameter ...
    );

K2_2slot_Static = ppval( ...
    K2_2slot_SplineStatic, ...
    deltafVector ...
    );

%% Plain Flap  (4)
smoothingParameter = 0.999999;
K2plain_SplineStatic = csaps( ...
    K2plain(:,1), ...
    K2plain(:,2), ...
    smoothingParameter ...
    );

K2plain_Static = ppval( ...
    K2plain_SplineStatic, ...
    deltafVector ...
    );

%% Fowler (5)
smoothingParameter = 0.999999;
K2Fowler_SplineStatic = csaps( ...
    K2Fowler(:,1), ...
    K2Fowler(:,2), ...
    smoothingParameter ...
    );

K2Fowler_Static = ppval( ...
    K2Fowler_SplineStatic, ...
    deltafVector ...
    );

%% 3-Slot  (6)
smoothingParameter = 0.999999;
K2_3slot_SplineStatic = csaps( ...
    K2_3slot(:,1), ...
    K2_3slot(:,2), ...
    smoothingParameter ...
    );

K2_3slot_Static = ppval( ...
    K2_3slot_SplineStatic, ...
    deltafVector ...
    );

%% Plots
figure(1)
plot ( ...
    deltafVector, K2_1slot_Static, 'b-*' ... , ...
 );

hold on;

plot ( ...
    deltafVector, K2_2slot_Static, 'b-+' ... , ...
 );

hold on;

plot ( ...
    deltafVector, K2plain_Static, 'b-.' ... , ...
 );

hold on;

plot ( ...
    deltafVector, K2Fowler_Static, 'b-^' ... , ...
 );

hold on;

plot ( ...
    deltafVector, K2_3slot_Static, 'b' ... , ...
 );

xlabel('\delta_f'); ylabel('K2');
 title('K2 coefficient variation with \delta_f');
 legend('1-Slot', '2-Slot', 'Plain Flap', 'Fowler', '3-Slot');
 
 axis([0 60 0 1]);
 grid on;
 %% preparing output to HDF
 
% FlapType (see number for each section)
flapTypeVector = [ ...
    1;2;3;4;5 ...
    ]; 
 
%columns --> curves
myData = [ ...
    K2_1slot_Static, ...
    K2_2slot_Static, ...
    K2plain_Static, ...
    K2Fowler_Static, ...
    K2_3slot_Static
    ];    
hdfFileName = 'K2_vs_deltaf.h5';

if ( exist(hdfFileName, 'file') )
    fprintf('file %s exists, deleting and creating a new one\n', hdfFileName);
    delete(hdfFileName)
else
    fprintf('Creating new file %s\n', hdfFileName);
end

% Dataset: data
h5create(hdfFileName, '/K2_vs_deltaf/data', size(myData'));
h5write(hdfFileName, '/K2_vs_deltaf/data', myData');

% Dataset: var_0
h5create(hdfFileName, '/K2_vs_deltaf/var_0', size(flapTypeVector'));
h5write(hdfFileName, '/K2_vs_deltaf/var_0', flapTypeVector');

% Dataset: var_1
h5create(hdfFileName, '/K2_vs_deltaf/var_1', size(deltafVector'));
h5write(hdfFileName, '/K2_vs_deltaf/var_1', deltafVector');