clc; close all; clear all;

%% Import data
K3_1slot = importdata('K31slot.mat');
K3_2slot = importdata('K32slot.mat');
K3plain = importdata('K31slot.mat');
K3fowler = importdata('K31slot.mat');
K3_3slot = importdata('K32slot.mat');

nPoints = 50;
df_dfRef_Vector = transpose(linspace(0, 1, nPoints));

%% 1-Slot  (1)
smoothingParameter = 0.999999;
K3_1slot_SplineStatic = csaps( ...
    K3_1slot(:,1), ...
    K3_1slot(:,2), ...
    smoothingParameter ...
    );

K3_1slot_Static = ppval( ...
    K3_1slot_SplineStatic, ...
    df_dfRef_Vector ...
    );

%% 2-Slot  (2)
smoothingParameter = 0.999999;
K3_2slot_SplineStatic = csaps( ...
    K3_2slot(:,1), ...
    K3_2slot(:,2), ...
    smoothingParameter ...
    );

K3_2slot_Static = ppval( ...
    K3_2slot_SplineStatic, ...
    df_dfRef_Vector ...
    );

%% Plain Flap  (4)
smoothingParameter = 0.999999;
K3plain_SplineStatic = csaps( ...
    K3plain(:,1), ...
    K3plain(:,2), ...
    smoothingParameter ...
    );

K3plain_Static = ppval( ...
    K3plain_SplineStatic, ...
    df_dfRef_Vector ...
    );

%% Fowler  (5)
smoothingParameter = 0.999999;
K3fowler_SplineStatic = csaps( ...
    K3fowler(:,1), ...
    K3fowler(:,2), ...
    smoothingParameter ...
    );

K3fowler_Static = ppval( ...
    K3fowler_SplineStatic, ...
    df_dfRef_Vector ...
    );

%% 3-Slot  (6)
smoothingParameter = 0.999999;
K3_3slot_SplineStatic = csaps( ...
    K3_3slot(:,1), ...
    K3_3slot(:,2), ...
    smoothingParameter ...
    );

K3_3slot_Static = ppval( ...
    K3_3slot_SplineStatic, ...
    df_dfRef_Vector ...
    );

%% Plots
figure(1)

plot ( ...
    df_dfRef_Vector, K3_1slot_Static, 'b-*' ... , ...
 );

hold on;

plot ( ...
    df_dfRef_Vector, K3_2slot_Static, 'b-+' ... , ...
 );

hold on;

plot ( ...
    df_dfRef_Vector, K3plain_Static, 'b-.' ... , ...
 );

hold on;

plot ( ...
    df_dfRef_Vector, K3fowler_Static, 'b-^' ... , ...
 );

hold on;

plot ( ...
    df_dfRef_Vector, K3_3slot_Static, 'b' ... , ...
 );

xlabel('\delta_f/\delta_{f ref}'); ylabel('K3');
 title('K3 coefficient variation with \delta_f/\delta_{f ref} ratio');
 legend('1-Slot', '2-Slot', 'Plain Flap', 'Fowler', '3-Slot');
 
 axis([0 1 0 1]);
 grid on;
 %% preparing output to HDF
 
% FlapType (see number for each section)
flapTypeVector = [ ...
    1;2;3;4;5 ...
    ]; 
 
%columns --> curves
myData = [ ...
    K3_1slot_Static, ...
    K3_2slot_Static, ...    
    K3plain_Static, ...
    K3fowler_Static, ...
    K3_3slot_Static
    ];    
hdfFileName = 'K3_vs_df_dfRef.h5';

if ( exist(hdfFileName, 'file') )
    fprintf('file %s exists, deleting and creating a new one\n', hdfFileName);
    delete(hdfFileName)
else
    fprintf('Creating new file %s\n', hdfFileName);
end

% Dataset: data
h5create(hdfFileName, '/K3_vs_df_dfRef/data', size(myData'));
h5write(hdfFileName, '/K3_vs_df_dfRef/data', myData');

% Dataset: var_0
h5create(hdfFileName, '/K3_vs_df_dfRef/var_0', size(flapTypeVector'));
h5write(hdfFileName, '/K3_vs_df_dfRef/var_0', flapTypeVector');

% Dataset: var_1
h5create(hdfFileName, '/K3_vs_df_dfRef/var_1', size(df_dfRef_Vector'));
h5write(hdfFileName, '/K3_vs_df_dfRef/var_1', df_dfRef_Vector');