clc; close all; clear all;

%% Import data
KbLambda0 = importdata('KbLambda0.mat');
KbLambda0p5 = importdata('KbLambda0p5.mat');
KbLambda1 = importdata('KbLambda1.mat');

nPoints = 50;
bf_b_Vector = transpose(linspace(0, 1, nPoints));

%% Taper Ratio = 0
smoothingParameter = 0.999999;
KbLambda0_SplineStatic = csaps( ...
    KbLambda0(:,1), ...
    KbLambda0(:,2), ...
    smoothingParameter ...
    );

KbLambda0_Static = ppval( ...
    KbLambda0_SplineStatic, ...
    bf_b_Vector ...
    );

%% Taper Ratio = 0.5
smoothingParameter = 0.999999;
KbLambda0p5_SplineStatic = csaps( ...
    KbLambda0p5(:,1), ...
    KbLambda0p5(:,2), ...
    smoothingParameter ...
    );

KbLambda0p5_Static = ppval( ...
    KbLambda0p5_SplineStatic, ...
    bf_b_Vector ...
    );

%% Taper Ratio = 1
smoothingParameter = 0.999999;
KbLambda1_SplineStatic = csaps( ...
    KbLambda1(:,1), ...
    KbLambda1(:,2), ...
    smoothingParameter ...
    );

KbLambda1_Static = ppval( ...
    KbLambda1_SplineStatic, ...
    bf_b_Vector ...
    );

%% Plots
figure(1)
plot ( ...
    bf_b_Vector, KbLambda0_Static, 'b-+' ... , ...
 );

hold on;

plot ( ...
    bf_b_Vector, KbLambda0p5_Static, 'b-o' ... , ...
 );

hold on;

plot ( ...
    bf_b_Vector, KbLambda1_Static, 'b-*' ... , ...
 );

xlabel('b_f/b'); ylabel('Kb');
 title('Kb coefficient variation with flap span ratio');
 legend('\lambda = 0', '\lambda = 0.5', '\lambda = 1');
 
 axis([0 1 0 1]);
 grid on;
 %% preparing output to HDF 

% Lambda
lambdaVector = [ ...
    0.0;0.5;1.0 ...
    ]; 
 
%columns --> curves
myData = [ ...
    KbLambda0_Static, ...
    KbLambda0p5_Static, ...
    KbLambda1_Static];    
hdfFileName = 'Kb_vs_flapSpanRatio.h5';

if ( exist(hdfFileName, 'file') )
    fprintf('file %s exists, deleting and creating a new one\n', hdfFileName);
    delete(hdfFileName)
else
    fprintf('Creating new file %s\n', hdfFileName);
end

% Dataset: data
h5create(hdfFileName, '/Kb_vs_flapSpanRatio/data', size(myData'));
h5write(hdfFileName, '/Kb_vs_flapSpanRatio/data', myData');

% Dataset: var_0
h5create(hdfFileName, '/Kb_vs_flapSpanRatio/var_0', size(lambdaVector'));
h5write(hdfFileName, '/Kb_vs_flapSpanRatio/var_0', lambdaVector');

% Dataset: var_1
h5create(hdfFileName, '/Kb_vs_flapSpanRatio/var_1', size(bf_b_Vector'));
h5write(hdfFileName, '/Kb_vs_flapSpanRatio/var_1', bf_b_Vector');
