clc; close all; clear all;

%% Import data
Kc_vs_AR_alphaDelta0p1 = importdata('Kc_alfaDelta_0p1.mat');
Kc_vs_AR_alphaDelta0p2 = importdata('Kc_alfaDelta_0p2.mat');
Kc_vs_AR_alphaDelta0p3 = importdata('Kc_alfaDelta_0p3.mat');
Kc_vs_AR_alphaDelta0p4 = importdata('Kc_alfaDelta_0p4.mat');
Kc_vs_AR_alphaDelta0p5 = importdata('Kc_alfaDelta_0p5.mat');
Kc_vs_AR_alphaDelta0p6 = importdata('Kc_alfaDelta_0p6.mat');
Kc_vs_AR_alphaDelta0p7 = importdata('Kc_alfaDelta_0p7.mat');
Kc_vs_AR_alphaDelta0p8 = importdata('Kc_alfaDelta_0p8.mat');

nPoints = 50;
ArVector = transpose(linspace(4, 10, nPoints));

%% alphaDelta = 0.1
smoothingParameter = 0.999999;
Kc_vs_AR_SplineStatic_alphaDelta0p1 = csaps( ...
    Kc_vs_AR_alphaDelta0p1(:,1), ...
    Kc_vs_AR_alphaDelta0p1(:,2), ...
    smoothingParameter ...
    );

Kc_vs_AR_Static_alphaDelta0p1 = ppval( ...
    Kc_vs_AR_SplineStatic_alphaDelta0p1, ...
    ArVector ...
    );

%% alphaDelta = 0.2
smoothingParameter = 0.999999;
Kc_vs_AR_SplineStatic_alphaDelta0p2 = csaps( ...
    Kc_vs_AR_alphaDelta0p2(:,1), ...
    Kc_vs_AR_alphaDelta0p2(:,2), ...
    smoothingParameter ...
    );

Kc_vs_AR_Static_alphaDelta0p2 = ppval( ...
    Kc_vs_AR_SplineStatic_alphaDelta0p2, ...
    ArVector ...
    );

%% alphaDelta = 0.3
smoothingParameter = 0.999999;
Kc_vs_AR_SplineStatic_alphaDelta0p3 = csaps( ...
    Kc_vs_AR_alphaDelta0p3(:,1), ...
    Kc_vs_AR_alphaDelta0p3(:,2), ...
    smoothingParameter ...
    );

Kc_vs_AR_Static_alphaDelta0p3 = ppval( ...
    Kc_vs_AR_SplineStatic_alphaDelta0p3, ...
    ArVector ...
    );

%% alphaDelta = 0.4
smoothingParameter = 0.999999;
Kc_vs_AR_SplineStatic_alphaDelta0p4 = csaps( ...
    Kc_vs_AR_alphaDelta0p4(:,1), ...
    Kc_vs_AR_alphaDelta0p4(:,2), ...
    smoothingParameter ...
    );

Kc_vs_AR_Static_alphaDelta0p4 = ppval( ...
    Kc_vs_AR_SplineStatic_alphaDelta0p4, ...
    ArVector ...
    );

%% alphaDelta = 0.5
smoothingParameter = 0.999999;
Kc_vs_AR_SplineStatic_alphaDelta0p5 = csaps( ...
    Kc_vs_AR_alphaDelta0p5(:,1), ...
    Kc_vs_AR_alphaDelta0p5(:,2), ...
    smoothingParameter ...
    );

Kc_vs_AR_Static_alphaDelta0p5 = ppval( ...
    Kc_vs_AR_SplineStatic_alphaDelta0p5, ...
    ArVector ...
    );

%% alphaDelta = 0.6
smoothingParameter = 0.999999;
Kc_vs_AR_SplineStatic_alphaDelta0p6 = csaps( ...
    Kc_vs_AR_alphaDelta0p6(:,1), ...
    Kc_vs_AR_alphaDelta0p6(:,2), ...
    smoothingParameter ...
    );

Kc_vs_AR_Static_alphaDelta0p6 = ppval( ...
    Kc_vs_AR_SplineStatic_alphaDelta0p6, ...
    ArVector ...
    );

%% alphaDelta = 0.7
smoothingParameter = 0.999999;
Kc_vs_AR_SplineStatic_alphaDelta0p7 = csaps( ...
    Kc_vs_AR_alphaDelta0p7(:,1), ...
    Kc_vs_AR_alphaDelta0p7(:,2), ...
    smoothingParameter ...
    );

Kc_vs_AR_Static_alphaDelta0p7 = ppval( ...
    Kc_vs_AR_SplineStatic_alphaDelta0p7, ...
    ArVector ...
    );

%% alphaDelta = 0.8
smoothingParameter = 0.999999;
Kc_vs_AR_SplineStatic_alphaDelta0p8 = csaps( ...
    Kc_vs_AR_alphaDelta0p8(:,1), ...
    Kc_vs_AR_alphaDelta0p8(:,2), ...
    smoothingParameter ...
    );

Kc_vs_AR_Static_alphaDelta0p8 = ppval( ...
    Kc_vs_AR_SplineStatic_alphaDelta0p8, ...
    ArVector ...
    );

%% Plots
figure(1)
plot ( ...
    ArVector, Kc_vs_AR_Static_alphaDelta0p1, 'b-+' ... , ...
 );
 hold on
 
 plot ( ...
    ArVector, Kc_vs_AR_Static_alphaDelta0p2, 'b-o' ... , ...
 );

hold on

plot ( ...
    ArVector, Kc_vs_AR_Static_alphaDelta0p3, 'b-*' ... , ...
 );

hold on

plot ( ...
    ArVector, Kc_vs_AR_Static_alphaDelta0p4, 'b-.' ... , ...
 );

hold on

plot ( ...
    ArVector, Kc_vs_AR_Static_alphaDelta0p5, 'b-x' ... , ...
 );

hold on

plot ( ...
    ArVector, Kc_vs_AR_Static_alphaDelta0p6, 'b-^' ... , ...
 );
hold on

plot ( ...
    ArVector, Kc_vs_AR_Static_alphaDelta0p7, 'b-v' ... , ...
 );
hold on

plot ( ...
    ArVector, Kc_vs_AR_Static_alphaDelta0p8, 'b' ... , ...
 );

 xlabel('AR'); ylabel('Kc');
 title('Kc coefficient variation with AR');
  legend('\alpha_{\delta} = 0.1', '\alpha_{\delta} = 0.2', '\alpha_{\delta} = 0.3',...
      '\alpha_{\delta} = 0.4', '\alpha_{\delta} = 0.5', '\alpha_{\delta} = 0.6',...
      '\alpha_{\delta} = 0.7', '\alpha_{\delta} = 0.8');
 axis([4 10 1 1.4]);
 grid on;
 %% preparing output to HDF

% alphaDelta
alphaDeltaVector = [ ...
    0.1;0.2;0.3;0.4;0.5;0.6;0.7;0.8 ...
    ];

%columns --> curves
myData = [ ...
    Kc_vs_AR_Static_alphaDelta0p1,...
        Kc_vs_AR_Static_alphaDelta0p2, ... 
        Kc_vs_AR_Static_alphaDelta0p3, ... 
        Kc_vs_AR_Static_alphaDelta0p4, ...
        Kc_vs_AR_Static_alphaDelta0p5, ...
        Kc_vs_AR_Static_alphaDelta0p6, ...
        Kc_vs_AR_Static_alphaDelta0p7, ...
        Kc_vs_AR_Static_alphaDelta0p8];    
hdfFileName = 'Kc_vs_AR_vs_alphaDelta.h5';

if ( exist(hdfFileName, 'file') )
    fprintf('file %s exists, deleting and creating a new one\n', hdfFileName);
    delete(hdfFileName)
else
    fprintf('Creating new file %s\n', hdfFileName);
end

% Dataset: data
h5create(hdfFileName, '/Kc_vs_AR_vs_alphaDelta/data', size(myData'));
h5write(hdfFileName, '/Kc_vs_AR_vs_alphaDelta/data', myData');

% Dataset: var_0
h5create(hdfFileName, '/Kc_vs_AR_vs_alphaDelta/var_0', size(alphaDeltaVector'));
h5write(hdfFileName, '/Kc_vs_AR_vs_alphaDelta/var_0', alphaDeltaVector');

% Dataset: var_1
h5create(hdfFileName, '/Kc_vs_AR_vs_alphaDelta/var_1', size(ArVector'));
h5write(hdfFileName, '/Kc_vs_AR_vs_alphaDelta/var_1', ArVector');

