clc; close all; clear all;

%% Import data
Mu1PitchingMomentPlaindeltaf10 = importdata('Mu1PitchingMomentPlaindeltaf10.mat');
Mu1PitchingMomentPlaindeltaf20 = importdata('Mu1PitchingMomentPlaindeltaf20.mat');
Mu1PitchingMomentPlaindeltaf30 = importdata('Mu1PitchingMomentPlaindeltaf30.mat');
Mu1PitchingMomentPlaindeltaf45 = importdata('Mu1PitchingMomentPlaindeltaf45.mat');
Mu1PitchingMomentPlaindeltaf60 = importdata('Mu1PitchingMomentPlaindeltaf60.mat');

nPoints = 50;
cf_c_First_Vector = transpose(linspace(0.1, 0.4, nPoints));

%% Mu_1 v.s cf_c' delta flap = 10°
smoothingParameter = 0.999999;
Mu1PitchingMomentPlaindeltaf10_SplineStatic = csaps( ...
    Mu1PitchingMomentPlaindeltaf10(:,1), ...
    Mu1PitchingMomentPlaindeltaf10(:,2), ...
    smoothingParameter ...
    );

Mu1PitchingMomentPlaindeltaf10_Static = ppval( ...
    Mu1PitchingMomentPlaindeltaf10_SplineStatic, ...
    cf_c_First_Vector ...
    );

%% Mu_1 v.s cf_c' delta flap = 20°
smoothingParameter = 0.999999;
Mu1PitchingMomentPlaindeltaf20_SplineStatic = csaps( ...
    Mu1PitchingMomentPlaindeltaf20(:,1), ...
    Mu1PitchingMomentPlaindeltaf20(:,2), ...
    smoothingParameter ...
    );

Mu1PitchingMomentPlaindeltaf20_Static = ppval( ...
    Mu1PitchingMomentPlaindeltaf20_SplineStatic, ...
    cf_c_First_Vector ...
    );

%% Mu_1 v.s cf_c' delta flap = 30°
smoothingParameter = 0.999999;
Mu1PitchingMomentPlaindeltaf30_SlpineStatic = csaps( ...
    Mu1PitchingMomentPlaindeltaf30(:,1), ...
    Mu1PitchingMomentPlaindeltaf30(:,2), ...
    smoothingParameter ...
    );

Mu1PitchingMomentPlaindeltaf30_Static = ppval( ...
    Mu1PitchingMomentPlaindeltaf30_SlpineStatic, ...
    cf_c_First_Vector ...
    );

%% Mu_1 v.s cf_c' delta flap = 45°
smoothingParameter = 0.999999;
Mu1PitchingMomentPlaindeltaf45_SplineStatic = csaps( ...
    Mu1PitchingMomentPlaindeltaf45(:,1), ...
    Mu1PitchingMomentPlaindeltaf45(:,2), ...
    smoothingParameter ...
    );

Mu1PitchingMomentPlaindeltaf45_Static = ppval( ...
    Mu1PitchingMomentPlaindeltaf45_SplineStatic, ...
    cf_c_First_Vector ...
    );

%% Mu_1 v.s cf_c' delta flap = 60°
smoothingParameter = 0.999999;
Mu1PitchingMomentPlaindeltaf60_SplineStatic = csaps( ...
    Mu1PitchingMomentPlaindeltaf60(:,1), ...
    Mu1PitchingMomentPlaindeltaf60(:,2), ...
    smoothingParameter ...
    );

Mu1PitchingMomentPlaindeltaf60_Static = ppval( ...
    Mu1PitchingMomentPlaindeltaf60_SplineStatic, ...
    cf_c_First_Vector ...
    );

%% Plots
figure(1)
plot ( ...
    cf_c_First_Vector, Mu1PitchingMomentPlaindeltaf10_Static, 'b-+' ... , ...
 );
 hold on
 
 plot ( ...
    cf_c_First_Vector, Mu1PitchingMomentPlaindeltaf20_Static, 'b-o' ... , ...
 );

hold on

plot ( ...
    cf_c_First_Vector, Mu1PitchingMomentPlaindeltaf30_Static, 'b-*' ... , ...
 );

hold on

plot ( ...
    cf_c_First_Vector, Mu1PitchingMomentPlaindeltaf45_Static, 'b-.' ... , ...
 );

hold on

plot ( ...
    cf_c_First_Vector, Mu1PitchingMomentPlaindeltaf60_Static, 'b-x' ... , ...
 );

 xlabel('c_f/c'''); ylabel('\mu_1');
 title('\mu_1 coefficient variation with c_f/c'' - Plain Flap');
  legend('\delta_{flap} = 10°', '\delta_{flap} = 20°', '\delta_{flap} = 30°', ...
      '\delta_{flap} = 45°', '\delta_{flap} = 60°');
 axis([0.1 0.4 0.1 0.3]);
 grid on;
 %% preparing output to HDF

% alphaDelta
delta_Flap_Vector = [ ...
    10;20;30;45;60 ...
    ];

%columns --> curves
myData = [ ...
    Mu1PitchingMomentPlaindeltaf10_Static,...
        Mu1PitchingMomentPlaindeltaf20_Static, ... 
        Mu1PitchingMomentPlaindeltaf30_Static, ... 
        Mu1PitchingMomentPlaindeltaf45_Static, ...
        Mu1PitchingMomentPlaindeltaf60_Static]; 
hdfFileName = 'Mu_1_pitching_moment_Plain.h5';

if ( exist(hdfFileName, 'file') )
    fprintf('file %s exists, deleting and creating a new one\n', hdfFileName);
    delete(hdfFileName)
else
    fprintf('Creating new file %s\n', hdfFileName);
end

% Dataset: data
h5create(hdfFileName, '/Mu_1_pitching_moment_Plain/data', size(myData'));
h5write(hdfFileName, '/Mu_1_pitching_moment_Plain/data', myData');

% Dataset: var_0
h5create(hdfFileName, '/Mu_1_pitching_moment_Plain/var_0', size(delta_Flap_Vector'));
h5write(hdfFileName, '/Mu_1_pitching_moment_Plain/var_0', delta_Flap_Vector');

% Dataset: var_1
h5create(hdfFileName, '/Mu_1_pitching_moment_Plain/var_1', size(cf_c_First_Vector'));
h5write(hdfFileName, '/Mu_1_pitching_moment_Plain/var_1', cf_c_First_Vector');
