clc; close all; clear all;

%% Import data
Mu3PitchingMomentTaper0 = importdata('Mu3PitchingMomentTaper0.mat');
Mu3PitchingMomentTaper0p2 = importdata('Mu3PitchingMomentTaper0p2.mat');
Mu3PitchingMomentTaper0p4 = importdata('Mu3PitchingMomentTaper0p4.mat');
Mu3PitchingMomentTaper0p6 = importdata('Mu3PitchingMomentTaper0p6.mat');
Mu3PitchingMomentTaper0p8 = importdata('Mu3PitchingMomentTaper0p8.mat');
Mu3PitchingMomentTaper1 = importdata('Mu3PitchingMomentTaper1.mat');

nPoints = 50;
bf_b_Vector = transpose(linspace(0, 1, nPoints));

%% Mu_3 v.s bf/b taper ratio = 0
smoothingParameter = 0.999999;
Mu3PitchingMomentTaper0_SplineStatic = csaps( ...
    Mu3PitchingMomentTaper0(:,1), ...
    Mu3PitchingMomentTaper0(:,2), ...
    smoothingParameter ...
    );

Mu3PitchingMomentTaper0_Static = ppval( ...
    Mu3PitchingMomentTaper0_SplineStatic, ...
    bf_b_Vector ...
    );

%% Mu_3 v.s bf/b taper ratio = 0.2
smoothingParameter = 0.999999;
Mu3PitchingMomentTaper0p2_SplineStatic = csaps( ...
    Mu3PitchingMomentTaper0p2(:,1), ...
    Mu3PitchingMomentTaper0p2(:,2), ...
    smoothingParameter ...
    );

Mu3PitchingMomentTaper0p2_Static = ppval( ...
    Mu3PitchingMomentTaper0p2_SplineStatic, ...
    bf_b_Vector ...
    );

%% Mu_3 v.s bf/b taper ratio = 0.4
smoothingParameter = 0.999999;
Mu3PitchingMomentTaper0p4_SlpineStatic = csaps( ...
    Mu3PitchingMomentTaper0p4(:,1), ...
    Mu3PitchingMomentTaper0p4(:,2), ...
    smoothingParameter ...
    );

Mu3PitchingMomentTaper0p4_Static = ppval( ...
    Mu3PitchingMomentTaper0p4_SlpineStatic, ...
    bf_b_Vector ...
    );

%% Mu_3 v.s bf/b taper ratio = 0.6
smoothingParameter = 0.999999;
Mu3PitchingMomentTaper0p6_SplineStatic = csaps( ...
    Mu3PitchingMomentTaper0p6(:,1), ...
    Mu3PitchingMomentTaper0p6(:,2), ...
    smoothingParameter ...
    );

Mu3PitchingMomentTaper0p6_Static = ppval( ...
    Mu3PitchingMomentTaper0p6_SplineStatic, ...
    bf_b_Vector ...
    );

%% Mu_3 v.s bf/b taper ratio = 0.8
smoothingParameter = 0.999999;
Mu3PitchingMomentTaper0p8_SplineStatic = csaps( ...
    Mu3PitchingMomentTaper0p8(:,1), ...
    Mu3PitchingMomentTaper0p8(:,2), ...
    smoothingParameter ...
    );

Mu3PitchingMomentTaper0p8_Static = ppval( ...
    Mu3PitchingMomentTaper0p8_SplineStatic, ...
    bf_b_Vector ...
    );

%% Mu_3 v.s bf/b taper ratio = 1
smoothingParameter = 0.999999;
Mu3PitchingMomentTaper1_SplineStatic = csaps( ...
    Mu3PitchingMomentTaper1(:,1), ...
    Mu3PitchingMomentTaper1(:,2), ...
    smoothingParameter ...
    );

Mu3PitchingMomentTaper1_Static = ppval( ...
    Mu3PitchingMomentTaper1_SplineStatic, ...
    bf_b_Vector ...
    );

%% Plots
figure(1)
plot ( ...
    bf_b_Vector, Mu3PitchingMomentTaper0_Static, 'b-+' ... , ...
 );
 hold on
 
 plot ( ...
    bf_b_Vector, Mu3PitchingMomentTaper0p2_Static, 'b-o' ... , ...
 );

hold on

plot ( ...
    bf_b_Vector, Mu3PitchingMomentTaper0p4_Static, 'b-*' ... , ...
 );

hold on

plot ( ...
    bf_b_Vector, Mu3PitchingMomentTaper0p6_Static, 'b-.' ... , ...
 );

hold on

plot ( ...
    bf_b_Vector, Mu3PitchingMomentTaper0p8_Static, 'b-x' ... , ...
 );

hold on

plot ( ...
    bf_b_Vector, Mu3PitchingMomentTaper1_Static, 'b-' ... , ...
 );

 xlabel('b_f/b'''); ylabel('\mu_3');
 title('\mu_3 coefficient variation with b_f/b''');
  legend('Taper Ratio = 0', 'Taper Ratio = 0.2', 'Taper Ratio = 0.4', ...
      'Taper Ratio = 0.6', 'Taper Ratio = 0.8', 'Taper Ratio = 1');
 axis([0 1 0 0.07]);
 grid on;
 %% preparing output to HDF

% alphaDelta
TaperRatio_Vector = [ ...
    0;0.2;0.4;0.6;0.8;1 ...
    ];

%columns --> curves
myData = [ ...
    Mu3PitchingMomentTaper0_Static,...
        Mu3PitchingMomentTaper0p2_Static, ... 
        Mu3PitchingMomentTaper0p4_Static, ... 
        Mu3PitchingMomentTaper0p6_Static, ...
        Mu3PitchingMomentTaper0p8_Static, ...
        Mu3PitchingMomentTaper1_Static]; 
hdfFileName = 'Mu_3_pitching_moment.h5';

if ( exist(hdfFileName, 'file') )
    fprintf('file %s exists, deleting and creating a new one\n', hdfFileName);
    delete(hdfFileName)
else
    fprintf('Creating new file %s\n', hdfFileName);
end

% Dataset: data
h5create(hdfFileName, '/Mu_3_pitching_moment/data', size(myData'));
h5write(hdfFileName, '/Mu_3_pitching_moment/data', myData');

% Dataset: var_0
h5create(hdfFileName, '/Mu_3_pitching_moment/var_0', size(TaperRatio_Vector'));
h5write(hdfFileName, '/Mu_3_pitching_moment/var_0', TaperRatio_Vector');

% Dataset: var_1
h5create(hdfFileName, '/Mu_3_pitching_moment/var_1', size(bf_b_Vector'));
h5write(hdfFileName, '/Mu_3_pitching_moment/var_1', bf_b_Vector');