clc; close all; clear all;

%% Import data
Digit4 = importdata('4_5Digit.mat');
Digit5 = importdata('4_5Digit.mat');
Series63 = importdata('63Series.mat');
Series64 = importdata('64Series.mat');
Series65 = importdata('65Series.mat');
Series66 = importdata('66Series.mat');
Biconvex = importdata('Biconvex.mat');
DoubleWedge = importdata('DoubleWedge.mat');

nPoints = 50;
tc_Vector = transpose(linspace(0, 0.20, nPoints));

%% 4 digit
smoothingParameter = 0.999999;
Digit4_SplineStatic = csaps( ...
    Digit4(:,1), ...
    Digit4(:,2), ...
    smoothingParameter ...
    );

Digit4_Static = ppval( ...
    Digit4_SplineStatic, ...
    tc_Vector ...
    );

%% 5 digit
smoothingParameter = 0.999999;
Digit5_SplineStatic = csaps( ...
    Digit5(:,1), ...
    Digit5(:,2), ...
    smoothingParameter ...
    );

Digit5_Static = ppval( ...
    Digit5_SplineStatic, ...
    tc_Vector ...
    );

%% 63 Series
smoothingParameter = 0.999999;
Series63_SplineStatic = csaps( ...
    Series63(:,1), ...
    Series63(:,2), ...
    smoothingParameter ...
    );

Series63_Static = ppval( ...
    Series63_SplineStatic, ...
    tc_Vector ...
    );

%% 64 Series
smoothingParameter = 0.999999;
Series64_SplineStatic = csaps( ...
    Series64(:,1), ...
    Series64(:,2), ...
    smoothingParameter ...
    );

Series64_Static = ppval( ...
    Series64_SplineStatic, ...
    tc_Vector ...
    );

%% 65 Series
smoothingParameter = 0.999999;
Series65_SplineStatic = csaps( ...
    Series65(:,1), ...
    Series65(:,2), ...
    smoothingParameter ...
    );

Series65_Static = ppval( ...
    Series65_SplineStatic, ...
    tc_Vector ...
    );

%% 66 Series
smoothingParameter = 0.999999;
Series66_SplineStatic = csaps( ...
    Series66(:,1), ...
    Series66(:,2), ...
    smoothingParameter ...
    );

Series66_Static = ppval( ...
    Series66_SplineStatic, ...
    tc_Vector ...
    );

%% Biconvex
smoothingParameter = 0.999999;
Biconvex_SplineStatic = csaps( ...
    Biconvex(:,1), ...
    Biconvex(:,2), ...
    smoothingParameter ...
    );

Biconvex_Static = ppval( ...
    Biconvex_SplineStatic, ...
    tc_Vector ...
    );

%% Double wedge
smoothingParameter = 0.999999;
DoubleWedge_SplineStatic = csaps( ...
    DoubleWedge(:,1), ...
    DoubleWedge(:,2), ...
    smoothingParameter ...
    );

DoubleWedge_Static = ppval( ...
    DoubleWedge_SplineStatic, ...
    tc_Vector ...
    );

%% Plots
figure(1)
plot ( ...
    tc_Vector, Digit4_Static, 'b-+' ... , ...
 );

hold on;

plot ( ...
    tc_Vector, Digit5_Static, 'b-o' ... , ...
 );

hold on;

plot ( ...
    tc_Vector, Series63_Static, 'b-*' ... , ...
 );

hold on;

plot ( ...
    tc_Vector(14:end), Series64_Static(14:end), 'b-.' ... , ...
 );

hold on;

plot ( ...
    tc_Vector(6:end), Series65_Static(6:end), 'b-x' ... , ...
 );

hold on;

plot ( ...
    tc_Vector, Series66_Static, 'b-^' ... , ...
 );

hold on;

plot ( ...
    tc_Vector, Biconvex_Static, 'b-' ... , ...
 );

hold on;

plot ( ...
    tc_Vector, DoubleWedge_Static, 'b-*' ... , ...
 );

hold on;

xlabel('t/c'); ylabel('\Delta y (%chord)');
 title('Variation of LE sharpness parameter with airfoil thickness ratio');
 legend('4 digit', '5 digit', '63 Series', '64 Series', '65 Series', ...
        '66 Series', 'Biconvex', 'Double wedge');
 
 axis([0 0.20 0 5]);
 grid on;
 %% preparing output to HDF 

% Airfoil families
airfoilFamiliesVector = [ ...
    1;2;3;4;5;6;7;8 ...
    ]; 
 
%columns --> curves
myData = [ ...
    Digit4_Static, ...
    Digit5_Static, ...
    Series63_Static, ...
    Series64_Static, ...
    Series65_Static, ...
    Series66_Static, ...
    Biconvex_Static, ...
    DoubleWedge_Static];    
hdfFileName = 'DeltaYvsThicknessRatio.h5';

if ( exist(hdfFileName, 'file') )
    fprintf('file %s exists, deleting and creating a new one\n', hdfFileName);
    delete(hdfFileName)
else
    fprintf('Creating new file %s\n', hdfFileName);
end

% Dataset: data
h5create(hdfFileName, '/DeltaYvsThicknessRatio/data', size(myData'));
h5write(hdfFileName, '/DeltaYvsThicknessRatio/data', myData');

% Dataset: var_0
h5create(hdfFileName, '/DeltaYvsThicknessRatio/var_0', size(airfoilFamiliesVector'));
h5write(hdfFileName, '/DeltaYvsThicknessRatio/var_0', airfoilFamiliesVector');

% Dataset: var_1
h5create(hdfFileName, '/DeltaYvsThicknessRatio/var_1', size(tc_Vector'));
h5write(hdfFileName, '/DeltaYvsThicknessRatio/var_1', tc_Vector');
