function dataTable = importJSBSimCSV(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   D150AGILE = IMPORTFILE(FILENAME) Reads data from text file FILENAME for
%   the default selection.
%
%   D150AGILE = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   D150AGILE = importfile('D150 AGILE.csv', 2, 58);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/12/05 18:12:48

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
%   column29: double (%f)
%	column30: double (%f)
%   column31: double (%f)
%	column32: double (%f)
%   column33: double (%f)
%	column34: double (%f)
%   column35: double (%f)
%	column36: double (%f)
%   column37: double (%f)
%	column38: double (%f)
%   column39: double (%f)
%	column40: double (%f)
%   column41: double (%f)
%	column42: double (%f)
%   column43: double (%f)
%	column44: double (%f)
%   column45: double (%f)
%	column46: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
dataTable = table(dataArray{1:end-1}, 'VariableNames', {'Time','fdmjsbsimaeroforcesdrag_basic_Mach','fdmjsbsimaerofunctiondrag_coeff_basic_Mach','fdmjsbsimaeroforcesside_basic_Mach','fdmjsbsimaerofunctionside_coeff_basic_Mach','fdmjsbsimaeroforceslift_basic_Mach','fdmjsbsimaerofunctionlift_coeff_basic_Mach','fdmjsbsimaeroforcesroll_basic_Mach','fdmjsbsimaerofunctionroll_coeff_basic_Mach','fdmjsbsimaeroforcespitch_basic_Mach','fdmjsbsimaerofunctionpitch_coeff_basic_Mach','fdmjsbsimaeroforcesyaw_basic_Mach','fdmjsbsimaerofunctionyaw_coeff_basic_Mach','fdmjsbsimaeroforcesproll_basic_Mach','fdmjsbsimaerofunctionproll_coeff_basic_Mach','fdmjsbsimaeroforcesppitch_basic_Mach','fdmjsbsimaerofunctionppitch_coeff_basic_Mach','fdmjsbsimaeroforcespyaw_basic_Mach','fdmjsbsimaerofunctionpyaw_coeff_basic_Mach','fdmjsbsimaeroforcesqroll_basic_Mach','fdmjsbsimaerofunctionqroll_coeff_basic_Mach','fdmjsbsimaeroforcesqpitch_basic_Mach','fdmjsbsimaerofunctionqpitch_coeff_basic_Mach','fdmjsbsimaeroforcesqyaw_basic_Mach','fdmjsbsimaerofunctionqyaw_coeff_basic_Mach','fdmjsbsimaeroforcesrroll_basic_Mach','fdmjsbsimaerofunctionrroll_coeff_basic_Mach','fdmjsbsimaeroforcesrpitch_basic_Mach','fdmjsbsimaerofunctionrpitch_coeff_basic_Mach','fdmjsbsimaeroforcesryaw_basic_Mach','fdmjsbsimaerofunctionryaw_coeff_basic_Mach','fdmjsbsimaeroalphadeg','fdmjsbsimaerobetadeg','fdmjsbsimaeroRe','fdmjsbsimvelocitiesmach','fdmjsbsimpropulsionenginethrustlbs','fdmjsbsimpropulsionengine1thrustlbs','fdmjsbsimpositionhslmeters','fdmjsbsimattitudephideg','fdmjsbsimattitudethetadeg','fdmjsbsimattitudepsideg','fdmjsbsimvelocitiesvtruekts','fdmjsbsimvelocitieshdotfps','fdmjsbsimvelocitiesprad_sec','fdmjsbsimvelocitiesqrad_sec','fdmjsbsimvelocitiesrrad_sec'});

