%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Lenovo PC\Documents\Project Matlab\Agile\jsbsim\D150 AGILE.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/12/05 16:56:14

%% Initialize variables.
filename = 'D150 AGILE.csv';

dataTable = importJSBSimCSV(filename);

%% Plot
subplot(3,1,1)
plot( ...
    dataTable.Time, dataTable.fdmjsbsimvelocitiesmach ...
    )
xlabel('t (s)');
ylabel('Mach');

subplot(3,1,2)
plot( ...
    dataTable.Time, dataTable.fdmjsbsimpropulsionenginethrustlbs, ...
    dataTable.Time, dataTable.fdmjsbsimpropulsionengine1thrustlbs ...
    )
xlabel('t (s)');
ylabel('Thrust (lbs)');

