clc;clear all;close all;
%% Initialize variables.
filename = 'D150 AGILE.csv';

dataTable = importJSBSimCSV(filename);

%% Plot
subplot(3,1,1)
plot( ...
    dataTable.Time, dataTable.fdmjsbsimvelocitiesmach ...
    )
xlabel('t (s)');
ylabel('Mach');

subplot(3,1,2)
plot( ...
    dataTable.Time, dataTable.fdmjsbsimpropulsionenginethrustlbs, ...
    dataTable.Time, dataTable.fdmjsbsimpropulsionengine1thrustlbs ...
    )
xlabel('t (s)');
ylabel('Thrust (lbs)');

figure()
plot( ...
    dataTable.Time, dataTable.fdmjsbsimaeroalphadeg, ...
    dataTable.Time, dataTable.fdmjsbsimaerobetadeg ...
    )
xlabel('t (s)');
ylabel('angle (°)');
legend('\alpha','\beta');

figure()
plot( ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientaileron_drag_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientelevator_drag_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientrudder_drag_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientflap_outer_drag_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientflap_inner_drag_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientdrag_basic_Mach ...
    )
xlabel('t (s)');
ylabel('Drag (psf)');
legend('aileron','elevator','rudder','outerFlap','innerFlap', 'clean');

figure()
plot( ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientaileron_lift_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientelevator_lift_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientrudder_lift_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientflap_outer_lift_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientflap_inner_lift_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientlift_basic_Mach ...
    )
xlabel('t (s)');
ylabel('lift (psf)');
legend('aileron','elevator','rudder','outerFlap','innerFlap', 'clean');

figure()
plot( ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientaileron_side_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientelevator_side_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientrudder_side_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientflap_outer_side_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientflap_inner_side_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientside_basic_Mach ...
    )
xlabel('t (s)');
ylabel('side (psf)');
legend('aileron','elevator','rudder','outerFlap','innerFlap', 'clean');

figure()
plot( ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientaileron_roll_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientelevator_roll_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientrudder_roll_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientflap_outer_roll_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientflap_inner_roll_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientroll_basic_Mach ...
    )
xlabel('t (s)');
ylabel('roll (psf*ft)');
legend('aileron','elevator','rudder','outerFlap','innerFlap', 'clean');

figure()
plot( ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientaileron_pitch_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientelevator_pitch_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientrudder_pitch_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientflap_outer_pitch_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientflap_inner_pitch_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientpitch_basic_Mach ...
    )
xlabel('t (s)');
ylabel('pitch (psf*ft)');
legend('aileron','elevator','rudder','outerFlap','innerFlap', 'clean');

figure()
plot( ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientaileron_yaw_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientelevator_yaw_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientrudder_yaw_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientflap_outer_yaw_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientflap_inner_yaw_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerocoefficientyaw_basic_Mach ...
    )
xlabel('t (s)');
ylabel('yaw (psf*ft)');
legend('aileron','elevator','rudder','outerFlap','innerFlap', 'clean');
%Start Coefficient
figure()
plot( ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionaileron_drag_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionelevator_drag_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionrudder_drag_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionflap_outer_drag_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionflap_inner_drag_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctiondrag_coeff_basic_Mach ...
    )
xlabel('t (s)');
ylabel('C_D');
legend('aileron','elevator','rudder','outerFlap','innerFlap', 'clean');

figure()
plot( ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionaileron_lift_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionelevator_lift_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionrudder_lift_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionflap_outer_lift_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionflap_inner_lift_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionlift_coeff_basic_Mach ...
    )
xlabel('t (s)');
ylabel('C_L');
legend('aileron','elevator','rudder','outerFlap','innerFlap', 'clean');

figure()
plot( ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionaileron_side_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionelevator_side_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionrudder_side_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionflap_outer_side_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionflap_inner_side_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionside_coeff_basic_Mach ...
    )
xlabel('t (s)');
ylabel('C_Y');
legend('aileron','elevator','rudder','outerFlap','innerFlap', 'clean');

figure()
plot( ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionaileron_roll_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionelevator_roll_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionrudder_roll_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionflap_outer_roll_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionflap_inner_roll_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionroll_coeff_basic_Mach ...
    )
xlabel('t (s)');
ylabel('C_Roll');
legend('aileron','elevator','rudder','outerFlap','innerFlap', 'clean');

figure()
plot( ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionaileron_pitch_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionelevator_pitch_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionrudder_pitch_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionflap_outer_pitch_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionflap_inner_pitch_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionpitch_coeff_basic_Mach ...
    )
xlabel('t (s)');
ylabel('C_M');
legend('aileron','elevator','rudder','outerFlap','innerFlap', 'clean');

figure()
plot( ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionaileron_yaw_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionelevator_yaw_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionrudder_yaw_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionflap_outer_yaw_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionflap_inner_yaw_coeff_basic_Mach, ...
    dataTable.Time, dataTable.fdmjsbsimaerofunctionyaw_coeff_basic_Mach ...
    )
xlabel('t (s)');
ylabel('C_N');
legend('aileron','elevator','rudder','outerFlap','innerFlap', 'clean');

