clear all, close all, clc

%% load data file generated by Grabit
% https://it.mathworks.com/matlabcentral/fileexchange/7173-grabit

fileBaseNames = {'Delta_epsilon_G_b_apex_frac_b_vs_frac_lambda_AR_4' , 'Delta_epsilon_G_b_apex_frac_b_vs_frac_lambda_AR_5' , 'Delta_epsilon_G_b_apex_frac_b_vs_frac_lambda_AR_7' , 'Delta_epsilon_G_b_apex_frac_b_vs_frac_lambda_AR_8' , 'Delta_epsilon_G_b_apex_frac_b_vs_frac_lambda_AR_9' , 'Delta_epsilon_G_b_apex_frac_b_vs_frac_lambda_AR_10'};
nPoints = 41;

xx = linspace(1, 5, nPoints);

for kFile = 1:length(fileBaseNames)
    
%     fileName = sprintf('%s.mat',fileBaseNames{kFile});
    s = load(fileBaseNames{kFile}, '-mat');

    % Allocate imported array to column variable names
    
    x{kFile} = s.(fileBaseNames{kFile})(:, 1);
    x{kFile}(end) = 5;
    
    y{kFile} = s.(fileBaseNames{kFile})(:, 2);
    %% Smoothing
    pp(kFile) = csaps(x{kFile}, y{kFile}, 0.999999);
    c{kFile} = ppval(pp(kFile), xx');
    data(:,kFile) = c{kFile};

    plot (xx', data(:,kFile), '-*');
    hold on
end
ylabel('$ \frac{b''_W}{b}$','interpreter','latex'); 
xlabel('$\frac{1}{\lambda}$','interpreter','latex');
set(get(gca,'ylabel'),'rotation',0)

title('Effective wing span in the presence of the ground');
axis([1 5 0.6 0.9]);
legend('4','5','7', '8','9','10');


%% preparing output to HDF

AR = [4 5 7 8 9 10]';
one_frac_lambda = xx';

 
%columns --> curves
 
hdfFileName = 'Delta_epsilon_G_b_apex_frac_b_vs_frac_lambda';

if ( exist(hdfFileName, 'file') )
    fprintf('file %s exists, deleting and creating a new one\n', hdfFileName);
    delete(hdfFileName)
else
    fprintf('Creating new file %s\n', hdfFileName);
end

h5create(hdfFileName, '/(Delta_epsilon_G)_b_apex_frac_b_vs_frac_lambda/data', size(data'));
h5write(hdfFileName, '/(Delta_epsilon_G)_b_apex_frac_b_vs_frac_lambda/data', data');

h5create(hdfFileName, '/(Delta_epsilon_G)_b_apex_frac_b_vs_frac_lambda/var_0', size(AR'));
h5write(hdfFileName, '/(Delta_epsilon_G)_b_apex_frac_b_vs_frac_lambda/var_0', AR');

h5create(hdfFileName, '/(Delta_epsilon_G)_b_apex_frac_b_vs_frac_lambda/var_1', size(one_frac_lambda'));
h5write(hdfFileName, '/(Delta_epsilon_G)_b_apex_frac_b_vs_frac_lambda/var_1', one_frac_lambda');

