/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Polygon_mesh_processing;
 import CGAL.Polyhedron_3.Polyhedron_3_Halfedge_handle; 
public class Halfedge_pair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Halfedge_pair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Halfedge_pair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_Polygon_mesh_processingJNI.delete_Halfedge_pair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Halfedge_pair() {
    this(CGAL_Polygon_mesh_processingJNI.new_Halfedge_pair__SWIG_0(), true);
  }

  public Halfedge_pair(Polyhedron_3_Halfedge_handle first, Polyhedron_3_Halfedge_handle second) {
    this(CGAL_Polygon_mesh_processingJNI.new_Halfedge_pair__SWIG_1(Polyhedron_3_Halfedge_handle.getCPtr(first), first, Polyhedron_3_Halfedge_handle.getCPtr(second), second), true);
  }

  public Halfedge_pair(Halfedge_pair p) {
    this(CGAL_Polygon_mesh_processingJNI.new_Halfedge_pair__SWIG_2(Halfedge_pair.getCPtr(p), p), true);
  }

  public void setFirst(Polyhedron_3_Halfedge_handle value) {
    CGAL_Polygon_mesh_processingJNI.Halfedge_pair_first_set(swigCPtr, this, Polyhedron_3_Halfedge_handle.getCPtr(value), value);
  }

  public Polyhedron_3_Halfedge_handle getFirst() {
    long cPtr = CGAL_Polygon_mesh_processingJNI.Halfedge_pair_first_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Polyhedron_3_Halfedge_handle(cPtr, false);
  }

  public void setSecond(Polyhedron_3_Halfedge_handle value) {
    CGAL_Polygon_mesh_processingJNI.Halfedge_pair_second_set(swigCPtr, this, Polyhedron_3_Halfedge_handle.getCPtr(value), value);
  }

  public Polyhedron_3_Halfedge_handle getSecond() {
    long cPtr = CGAL_Polygon_mesh_processingJNI.Halfedge_pair_second_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Polyhedron_3_Halfedge_handle(cPtr, false);
  }

}
