/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Polygon_mesh_processing;

public class Int_Vector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Int_Vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Int_Vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_Polygon_mesh_processingJNI.delete_Int_Vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Int_Vector() {
    this(CGAL_Polygon_mesh_processingJNI.new_Int_Vector__SWIG_0(), true);
  }

  public Int_Vector(long n) {
    this(CGAL_Polygon_mesh_processingJNI.new_Int_Vector__SWIG_1(n), true);
  }

  public long size() {
    return CGAL_Polygon_mesh_processingJNI.Int_Vector_size(swigCPtr, this);
  }

  public long capacity() {
    return CGAL_Polygon_mesh_processingJNI.Int_Vector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    CGAL_Polygon_mesh_processingJNI.Int_Vector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return CGAL_Polygon_mesh_processingJNI.Int_Vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    CGAL_Polygon_mesh_processingJNI.Int_Vector_clear(swigCPtr, this);
  }

  public void add(int x) {
    CGAL_Polygon_mesh_processingJNI.Int_Vector_add(swigCPtr, this, x);
  }

  public int get(int i) {
    return CGAL_Polygon_mesh_processingJNI.Int_Vector_get(swigCPtr, this, i);
  }

  public void set(int i, int val) {
    CGAL_Polygon_mesh_processingJNI.Int_Vector_set(swigCPtr, this, i, val);
  }

}
