/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Polygon_mesh_processing;

public class Integer_triple {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Integer_triple(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Integer_triple obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_Polygon_mesh_processingJNI.delete_Integer_triple(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFirst(int value) {
    CGAL_Polygon_mesh_processingJNI.Integer_triple_first_set(swigCPtr, this, value);
  }

  public int getFirst() {
    return CGAL_Polygon_mesh_processingJNI.Integer_triple_first_get(swigCPtr, this);
  }

  public void setSecond(int value) {
    CGAL_Polygon_mesh_processingJNI.Integer_triple_second_set(swigCPtr, this, value);
  }

  public int getSecond() {
    return CGAL_Polygon_mesh_processingJNI.Integer_triple_second_get(swigCPtr, this);
  }

  public void setThird(int value) {
    CGAL_Polygon_mesh_processingJNI.Integer_triple_third_set(swigCPtr, this, value);
  }

  public int getThird() {
    return CGAL_Polygon_mesh_processingJNI.Integer_triple_third_get(swigCPtr, this);
  }

  public Integer_triple() {
    this(CGAL_Polygon_mesh_processingJNI.new_Integer_triple__SWIG_0(), true);
  }

  public Integer_triple(int a, int b, int c) {
    this(CGAL_Polygon_mesh_processingJNI.new_Integer_triple__SWIG_1(a, b, c), true);
  }

  public Integer_triple clone() {
    return new Integer_triple(CGAL_Polygon_mesh_processingJNI.Integer_triple_clone__SWIG_0(swigCPtr, this), true);
  }

  public void clone(Integer_triple other) {
    CGAL_Polygon_mesh_processingJNI.Integer_triple_clone__SWIG_1(swigCPtr, this, Integer_triple.getCPtr(other), other);
  }

}
