/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Polygon_mesh_processing;
 import CGAL.Kernel.Point_3; 
public class Point_3_Vector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Point_3_Vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Point_3_Vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_Polygon_mesh_processingJNI.delete_Point_3_Vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Point_3_Vector() {
    this(CGAL_Polygon_mesh_processingJNI.new_Point_3_Vector__SWIG_0(), true);
  }

  public Point_3_Vector(long n) {
    this(CGAL_Polygon_mesh_processingJNI.new_Point_3_Vector__SWIG_1(n), true);
  }

  public long size() {
    return CGAL_Polygon_mesh_processingJNI.Point_3_Vector_size(swigCPtr, this);
  }

  public long capacity() {
    return CGAL_Polygon_mesh_processingJNI.Point_3_Vector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    CGAL_Polygon_mesh_processingJNI.Point_3_Vector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return CGAL_Polygon_mesh_processingJNI.Point_3_Vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    CGAL_Polygon_mesh_processingJNI.Point_3_Vector_clear(swigCPtr, this);
  }

  public void add(Point_3 x) {
    CGAL_Polygon_mesh_processingJNI.Point_3_Vector_add(swigCPtr, this, Point_3.getCPtr(x), x);
  }

  public Point_3 get(int i) {
    return new Point_3(CGAL_Polygon_mesh_processingJNI.Point_3_Vector_get(swigCPtr, this, i), false);
  }

  public void set(int i, Point_3 val) {
    CGAL_Polygon_mesh_processingJNI.Point_3_Vector_set(swigCPtr, this, i, Point_3.getCPtr(val), val);
  }

}
