/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Kernel;

public class Bbox_3 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Bbox_3(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Bbox_3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_KernelJNI.delete_Bbox_3(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Bbox_3() {
    this(CGAL_KernelJNI.new_Bbox_3__SWIG_0(), true);
  }

  public Bbox_3(double x_min, double y_min, double z_min, double x_max, double y_max, double z_max) {
    this(CGAL_KernelJNI.new_Bbox_3__SWIG_1(x_min, y_min, z_min, x_max, y_max, z_max), true);
  }

  public int dimension() {
    return CGAL_KernelJNI.Bbox_3_dimension(swigCPtr, this);
  }

  public double xmin() {
    return CGAL_KernelJNI.Bbox_3_xmin(swigCPtr, this);
  }

  public double ymin() {
    return CGAL_KernelJNI.Bbox_3_ymin(swigCPtr, this);
  }

  public double zmin() {
    return CGAL_KernelJNI.Bbox_3_zmin(swigCPtr, this);
  }

  public double xmax() {
    return CGAL_KernelJNI.Bbox_3_xmax(swigCPtr, this);
  }

  public double ymax() {
    return CGAL_KernelJNI.Bbox_3_ymax(swigCPtr, this);
  }

  public double zmax() {
    return CGAL_KernelJNI.Bbox_3_zmax(swigCPtr, this);
  }

  public double min(int i) {
    return CGAL_KernelJNI.Bbox_3_min(swigCPtr, this, i);
  }

  public double max(int i) {
    return CGAL_KernelJNI.Bbox_3_max(swigCPtr, this, i);
  }

  public Bbox_3 plus(Bbox_3 c) {
    return new Bbox_3(CGAL_KernelJNI.Bbox_3_plus(swigCPtr, this, Bbox_3.getCPtr(c), c), true);
  }

  public Bbox_3 iplus(Bbox_3 c) {
    return new Bbox_3(CGAL_KernelJNI.Bbox_3_iplus(swigCPtr, this, Bbox_3.getCPtr(c), c), false);
  }

  public boolean equals(Bbox_3 p) {
    return CGAL_KernelJNI.Bbox_3_equals(swigCPtr, this, Bbox_3.getCPtr(p), p);
  }

  public boolean not_equals(Bbox_3 p) {
    return CGAL_KernelJNI.Bbox_3_not_equals(swigCPtr, this, Bbox_3.getCPtr(p), p);
  }

  public String toString() {
    return CGAL_KernelJNI.Bbox_3_toString(swigCPtr, this);
  }

  public Bbox_3 clone() {
    return new Bbox_3(CGAL_KernelJNI.Bbox_3_clone__SWIG_0(swigCPtr, this), true);
  }

  public void clone(Bbox_3 other) {
    CGAL_KernelJNI.Bbox_3_clone__SWIG_1(swigCPtr, this, Bbox_3.getCPtr(other), other);
  }

}
