/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Kernel;

public class Point_2 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Point_2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Point_2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_KernelJNI.delete_Point_2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Point_2() {
    this(CGAL_KernelJNI.new_Point_2__SWIG_0(), true);
  }

  public Point_2(Origin arg0) {
    this(CGAL_KernelJNI.new_Point_2__SWIG_1(Origin.getCPtr(arg0), arg0), true);
  }

  public Point_2(double x, double y) {
    this(CGAL_KernelJNI.new_Point_2__SWIG_2(x, y), true);
  }

  public double x() {
    return CGAL_KernelJNI.Point_2_x(swigCPtr, this);
  }

  public double y() {
    return CGAL_KernelJNI.Point_2_y(swigCPtr, this);
  }

  public Bbox_2 bbox() {
    return new Bbox_2(CGAL_KernelJNI.Point_2_bbox__SWIG_0(swigCPtr, this), true);
  }

  public void bbox(Bbox_2 ref) {
    CGAL_KernelJNI.Point_2_bbox__SWIG_1(swigCPtr, this, Bbox_2.getCPtr(ref), ref);
  }

  public void set_coordinates(double x, double y) {
    CGAL_KernelJNI.Point_2_set_coordinates(swigCPtr, this, x, y);
  }

  public String toString() {
    return CGAL_KernelJNI.Point_2_toString(swigCPtr, this);
  }

  public Vector_2 minus(Point_2 arg0) {
    return new Vector_2(CGAL_KernelJNI.Point_2_minus__SWIG_0(swigCPtr, this, Point_2.getCPtr(arg0), arg0), true);
  }

  public Point_2 plus(Vector_2 arg0) {
    return new Point_2(CGAL_KernelJNI.Point_2_plus(swigCPtr, this, Vector_2.getCPtr(arg0), arg0), true);
  }

  public Point_2 minus(Vector_2 arg0) {
    return new Point_2(CGAL_KernelJNI.Point_2_minus__SWIG_1(swigCPtr, this, Vector_2.getCPtr(arg0), arg0), true);
  }

  public Vector_2 minus(Origin arg0) {
    return new Vector_2(CGAL_KernelJNI.Point_2_minus__SWIG_2(swigCPtr, this, Origin.getCPtr(arg0), arg0), true);
  }

  public boolean equals(Origin arg0) {
    return CGAL_KernelJNI.Point_2_equals__SWIG_0(swigCPtr, this, Origin.getCPtr(arg0), arg0);
  }

  public boolean lt(Point_2 p) {
    return CGAL_KernelJNI.Point_2_lt(swigCPtr, this, Point_2.getCPtr(p), p);
  }

  public boolean gt(Point_2 p) {
    return CGAL_KernelJNI.Point_2_gt(swigCPtr, this, Point_2.getCPtr(p), p);
  }

  public boolean le(Point_2 p) {
    return CGAL_KernelJNI.Point_2_le(swigCPtr, this, Point_2.getCPtr(p), p);
  }

  public boolean ge(Point_2 p) {
    return CGAL_KernelJNI.Point_2_ge(swigCPtr, this, Point_2.getCPtr(p), p);
  }

  public boolean equals(Point_2 p) {
    return CGAL_KernelJNI.Point_2_equals__SWIG_1(swigCPtr, this, Point_2.getCPtr(p), p);
  }

  public boolean not_equals(Point_2 p) {
    return CGAL_KernelJNI.Point_2_not_equals(swigCPtr, this, Point_2.getCPtr(p), p);
  }

  public Point_2 iplus(Vector_2 arg0) {
    return new Point_2(CGAL_KernelJNI.Point_2_iplus(swigCPtr, this, Vector_2.getCPtr(arg0), arg0), false);
  }

  public Point_2 iminus(Vector_2 arg0) {
    return new Point_2(CGAL_KernelJNI.Point_2_iminus(swigCPtr, this, Vector_2.getCPtr(arg0), arg0), false);
  }

  public Point_2 clone() {
    return new Point_2(CGAL_KernelJNI.Point_2_clone__SWIG_0(swigCPtr, this), true);
  }

  public void clone(Point_2 other) {
    CGAL_KernelJNI.Point_2_clone__SWIG_1(swigCPtr, this, Point_2.getCPtr(other), other);
  }

}
