/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Kernel;

public class Triangle_2 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Triangle_2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Triangle_2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_KernelJNI.delete_Triangle_2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Triangle_2() {
    this(CGAL_KernelJNI.new_Triangle_2__SWIG_0(), true);
  }

  public Triangle_2(Point_2 p, Point_2 q, Point_2 r) {
    this(CGAL_KernelJNI.new_Triangle_2__SWIG_1(Point_2.getCPtr(p), p, Point_2.getCPtr(q), q, Point_2.getCPtr(r), r), true);
  }

  public Point_2 vertex(int c) {
    return new Point_2(CGAL_KernelJNI.Triangle_2_vertex__SWIG_0(swigCPtr, this, c), true);
  }

  public void vertex(int c, Point_2 ret) {
    CGAL_KernelJNI.Triangle_2_vertex__SWIG_1(swigCPtr, this, c, Point_2.getCPtr(ret), ret);
  }

  public boolean is_degenerate() {
    return CGAL_KernelJNI.Triangle_2_is_degenerate(swigCPtr, this);
  }

  public boolean has_on_positive_side(Point_2 c) {
    return CGAL_KernelJNI.Triangle_2_has_on_positive_side(swigCPtr, this, Point_2.getCPtr(c), c);
  }

  public boolean has_on_negative_side(Point_2 c) {
    return CGAL_KernelJNI.Triangle_2_has_on_negative_side(swigCPtr, this, Point_2.getCPtr(c), c);
  }

  public boolean has_on_boundary(Point_2 c) {
    return CGAL_KernelJNI.Triangle_2_has_on_boundary(swigCPtr, this, Point_2.getCPtr(c), c);
  }

  public boolean has_on_bounded_side(Point_2 c) {
    return CGAL_KernelJNI.Triangle_2_has_on_bounded_side(swigCPtr, this, Point_2.getCPtr(c), c);
  }

  public boolean has_on_unbounded_side(Point_2 c) {
    return CGAL_KernelJNI.Triangle_2_has_on_unbounded_side(swigCPtr, this, Point_2.getCPtr(c), c);
  }

  public Orientation orientation() {
    return Orientation.swigToEnum(CGAL_KernelJNI.Triangle_2_orientation(swigCPtr, this));
  }

  public Oriented_side oriented_side(Point_2 c) {
    return Oriented_side.swigToEnum(CGAL_KernelJNI.Triangle_2_oriented_side(swigCPtr, this, Point_2.getCPtr(c), c));
  }

  public Bounded_side bounded_side(Point_2 c) {
    return Bounded_side.swigToEnum(CGAL_KernelJNI.Triangle_2_bounded_side(swigCPtr, this, Point_2.getCPtr(c), c));
  }

  public Triangle_2 opposite() {
    return new Triangle_2(CGAL_KernelJNI.Triangle_2_opposite__SWIG_0(swigCPtr, this), true);
  }

  public void opposite(Triangle_2 ref) {
    CGAL_KernelJNI.Triangle_2_opposite__SWIG_1(swigCPtr, this, Triangle_2.getCPtr(ref), ref);
  }

  public double area() {
    return CGAL_KernelJNI.Triangle_2_area(swigCPtr, this);
  }

  public Bbox_2 bbox() {
    return new Bbox_2(CGAL_KernelJNI.Triangle_2_bbox__SWIG_0(swigCPtr, this), true);
  }

  public void bbox(Bbox_2 ref) {
    CGAL_KernelJNI.Triangle_2_bbox__SWIG_1(swigCPtr, this, Bbox_2.getCPtr(ref), ref);
  }

  public boolean equals(Triangle_2 p) {
    return CGAL_KernelJNI.Triangle_2_equals(swigCPtr, this, Triangle_2.getCPtr(p), p);
  }

  public boolean not_equals(Triangle_2 p) {
    return CGAL_KernelJNI.Triangle_2_not_equals(swigCPtr, this, Triangle_2.getCPtr(p), p);
  }

  public String toString() {
    return CGAL_KernelJNI.Triangle_2_toString(swigCPtr, this);
  }

  public Triangle_2 clone() {
    return new Triangle_2(CGAL_KernelJNI.Triangle_2_clone__SWIG_0(swigCPtr, this), true);
  }

  public void clone(Triangle_2 other) {
    CGAL_KernelJNI.Triangle_2_clone__SWIG_1(swigCPtr, this, Triangle_2.getCPtr(other), other);
  }

}
