/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Kernel;

public class Vector_2 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Vector_2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Vector_2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_KernelJNI.delete_Vector_2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Vector_2() {
    this(CGAL_KernelJNI.new_Vector_2__SWIG_0(), true);
  }

  public Vector_2(Null_vector arg0) {
    this(CGAL_KernelJNI.new_Vector_2__SWIG_1(Null_vector.getCPtr(arg0), arg0), true);
  }

  public Vector_2(Point_2 a, Point_2 b) {
    this(CGAL_KernelJNI.new_Vector_2__SWIG_2(Point_2.getCPtr(a), a, Point_2.getCPtr(b), b), true);
  }

  public Vector_2(Segment_2 s) {
    this(CGAL_KernelJNI.new_Vector_2__SWIG_3(Segment_2.getCPtr(s), s), true);
  }

  public Vector_2(Ray_2 r) {
    this(CGAL_KernelJNI.new_Vector_2__SWIG_4(Ray_2.getCPtr(r), r), true);
  }

  public Vector_2(Line_2 l) {
    this(CGAL_KernelJNI.new_Vector_2__SWIG_5(Line_2.getCPtr(l), l), true);
  }

  public Vector_2(int x, int y) {
    this(CGAL_KernelJNI.new_Vector_2__SWIG_6(x, y), true);
  }

  public Vector_2(double x, double y) {
    this(CGAL_KernelJNI.new_Vector_2__SWIG_7(x, y), true);
  }

  public double x() {
    return CGAL_KernelJNI.Vector_2_x(swigCPtr, this);
  }

  public double y() {
    return CGAL_KernelJNI.Vector_2_y(swigCPtr, this);
  }

  public double cartesian(int c) {
    return CGAL_KernelJNI.Vector_2_cartesian(swigCPtr, this, c);
  }

  public int dimension() {
    return CGAL_KernelJNI.Vector_2_dimension(swigCPtr, this);
  }

  public Direction_2 direction() {
    return new Direction_2(CGAL_KernelJNI.Vector_2_direction__SWIG_0(swigCPtr, this), true);
  }

  public void direction(Direction_2 ref) {
    CGAL_KernelJNI.Vector_2_direction__SWIG_1(swigCPtr, this, Direction_2.getCPtr(ref), ref);
  }

  public Vector_2 perpendicular(Orientation c) {
    return new Vector_2(CGAL_KernelJNI.Vector_2_perpendicular__SWIG_0(swigCPtr, this, c.swigValue()), true);
  }

  public void perpendicular(Orientation c, Vector_2 ret) {
    CGAL_KernelJNI.Vector_2_perpendicular__SWIG_1(swigCPtr, this, c.swigValue(), Vector_2.getCPtr(ret), ret);
  }

  public double squared_length() {
    return CGAL_KernelJNI.Vector_2_squared_length(swigCPtr, this);
  }

  public Vector_2 plus(Vector_2 c) {
    return new Vector_2(CGAL_KernelJNI.Vector_2_plus(swigCPtr, this, Vector_2.getCPtr(c), c), true);
  }

  public Vector_2 minus(Vector_2 c) {
    return new Vector_2(CGAL_KernelJNI.Vector_2_minus__SWIG_0(swigCPtr, this, Vector_2.getCPtr(c), c), true);
  }

  public Vector_2 minus() {
    return new Vector_2(CGAL_KernelJNI.Vector_2_minus__SWIG_1(swigCPtr, this), true);
  }

  public double times(Vector_2 v) {
    return CGAL_KernelJNI.Vector_2_times__SWIG_0(swigCPtr, this, Vector_2.getCPtr(v), v);
  }

  public Vector_2 times(double d) {
    return new Vector_2(CGAL_KernelJNI.Vector_2_times__SWIG_1(swigCPtr, this, d), true);
  }

  public Vector_2 div(double c) {
    return new Vector_2(CGAL_KernelJNI.Vector_2_div(swigCPtr, this, c), true);
  }

  public boolean equals(Null_vector arg0) {
    return CGAL_KernelJNI.Vector_2_equals__SWIG_0(swigCPtr, this, Null_vector.getCPtr(arg0), arg0);
  }

  public boolean equals(Vector_2 p) {
    return CGAL_KernelJNI.Vector_2_equals__SWIG_1(swigCPtr, this, Vector_2.getCPtr(p), p);
  }

  public boolean not_equals(Vector_2 p) {
    return CGAL_KernelJNI.Vector_2_not_equals(swigCPtr, this, Vector_2.getCPtr(p), p);
  }

  public Vector_2 iplus(Vector_2 v) {
    return new Vector_2(CGAL_KernelJNI.Vector_2_iplus(swigCPtr, this, Vector_2.getCPtr(v), v), false);
  }

  public Vector_2 iminus(Vector_2 v) {
    return new Vector_2(CGAL_KernelJNI.Vector_2_iminus(swigCPtr, this, Vector_2.getCPtr(v), v), false);
  }

  public Vector_2 itimes(double d) {
    return new Vector_2(CGAL_KernelJNI.Vector_2_itimes(swigCPtr, this, d), false);
  }

  public Vector_2 idiv(double d) {
    return new Vector_2(CGAL_KernelJNI.Vector_2_idiv(swigCPtr, this, d), false);
  }

  public String toString() {
    return CGAL_KernelJNI.Vector_2_toString(swigCPtr, this);
  }

  public Vector_2 clone() {
    return new Vector_2(CGAL_KernelJNI.Vector_2_clone__SWIG_0(swigCPtr, this), true);
  }

  public void clone(Vector_2 other) {
    CGAL_KernelJNI.Vector_2_clone__SWIG_1(swigCPtr, this, Vector_2.getCPtr(other), other);
  }

  public void normalize() {
    CGAL_KernelJNI.Vector_2_normalize(swigCPtr, this);
  }

}
