/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Kernel;

public class Vector_3 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Vector_3(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Vector_3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_KernelJNI.delete_Vector_3(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Vector_3() {
    this(CGAL_KernelJNI.new_Vector_3__SWIG_0(), true);
  }

  public Vector_3(Null_vector arg0) {
    this(CGAL_KernelJNI.new_Vector_3__SWIG_1(Null_vector.getCPtr(arg0), arg0), true);
  }

  public Vector_3(Point_3 a, Point_3 b) {
    this(CGAL_KernelJNI.new_Vector_3__SWIG_2(Point_3.getCPtr(a), a, Point_3.getCPtr(b), b), true);
  }

  public Vector_3(Segment_3 s) {
    this(CGAL_KernelJNI.new_Vector_3__SWIG_3(Segment_3.getCPtr(s), s), true);
  }

  public Vector_3(Ray_3 r) {
    this(CGAL_KernelJNI.new_Vector_3__SWIG_4(Ray_3.getCPtr(r), r), true);
  }

  public Vector_3(Line_3 l) {
    this(CGAL_KernelJNI.new_Vector_3__SWIG_5(Line_3.getCPtr(l), l), true);
  }

  public Vector_3(int x, int y, int z) {
    this(CGAL_KernelJNI.new_Vector_3__SWIG_6(x, y, z), true);
  }

  public Vector_3(double x, double y, double z) {
    this(CGAL_KernelJNI.new_Vector_3__SWIG_7(x, y, z), true);
  }

  public double x() {
    return CGAL_KernelJNI.Vector_3_x(swigCPtr, this);
  }

  public double y() {
    return CGAL_KernelJNI.Vector_3_y(swigCPtr, this);
  }

  public double z() {
    return CGAL_KernelJNI.Vector_3_z(swigCPtr, this);
  }

  public double cartesian(int c) {
    return CGAL_KernelJNI.Vector_3_cartesian(swigCPtr, this, c);
  }

  public Direction_3 direction() {
    return new Direction_3(CGAL_KernelJNI.Vector_3_direction__SWIG_0(swigCPtr, this), true);
  }

  public void direction(Direction_3 ref) {
    CGAL_KernelJNI.Vector_3_direction__SWIG_1(swigCPtr, this, Direction_3.getCPtr(ref), ref);
  }

  public double squared_length() {
    return CGAL_KernelJNI.Vector_3_squared_length(swigCPtr, this);
  }

  public int dimension() {
    return CGAL_KernelJNI.Vector_3_dimension(swigCPtr, this);
  }

  public Vector_3 plus(Vector_3 c) {
    return new Vector_3(CGAL_KernelJNI.Vector_3_plus(swigCPtr, this, Vector_3.getCPtr(c), c), true);
  }

  public Vector_3 minus(Vector_3 c) {
    return new Vector_3(CGAL_KernelJNI.Vector_3_minus__SWIG_0(swigCPtr, this, Vector_3.getCPtr(c), c), true);
  }

  public Vector_3 minus() {
    return new Vector_3(CGAL_KernelJNI.Vector_3_minus__SWIG_1(swigCPtr, this), true);
  }

  public double times(Vector_3 v) {
    return CGAL_KernelJNI.Vector_3_times__SWIG_0(swigCPtr, this, Vector_3.getCPtr(v), v);
  }

  public Vector_3 times(double d) {
    return new Vector_3(CGAL_KernelJNI.Vector_3_times__SWIG_1(swigCPtr, this, d), true);
  }

  public Vector_3 div(double c) {
    return new Vector_3(CGAL_KernelJNI.Vector_3_div(swigCPtr, this, c), true);
  }

  public boolean equals(Null_vector arg0) {
    return CGAL_KernelJNI.Vector_3_equals__SWIG_0(swigCPtr, this, Null_vector.getCPtr(arg0), arg0);
  }

  public boolean equals(Vector_3 p) {
    return CGAL_KernelJNI.Vector_3_equals__SWIG_1(swigCPtr, this, Vector_3.getCPtr(p), p);
  }

  public boolean not_equals(Vector_3 p) {
    return CGAL_KernelJNI.Vector_3_not_equals(swigCPtr, this, Vector_3.getCPtr(p), p);
  }

  public Vector_3 iplus(Vector_3 v) {
    return new Vector_3(CGAL_KernelJNI.Vector_3_iplus(swigCPtr, this, Vector_3.getCPtr(v), v), false);
  }

  public Vector_3 iminus(Vector_3 v) {
    return new Vector_3(CGAL_KernelJNI.Vector_3_iminus(swigCPtr, this, Vector_3.getCPtr(v), v), false);
  }

  public Vector_3 itimes(double d) {
    return new Vector_3(CGAL_KernelJNI.Vector_3_itimes(swigCPtr, this, d), false);
  }

  public Vector_3 idiv(double d) {
    return new Vector_3(CGAL_KernelJNI.Vector_3_idiv(swigCPtr, this, d), false);
  }

  public void set_coordinates(double x, double y, double z) {
    CGAL_KernelJNI.Vector_3_set_coordinates(swigCPtr, this, x, y, z);
  }

  public String toString() {
    return CGAL_KernelJNI.Vector_3_toString(swigCPtr, this);
  }

  public Vector_3 clone() {
    return new Vector_3(CGAL_KernelJNI.Vector_3_clone__SWIG_0(swigCPtr, this), true);
  }

  public void clone(Vector_3 other) {
    CGAL_KernelJNI.Vector_3_clone__SWIG_1(swigCPtr, this, Vector_3.getCPtr(other), other);
  }

  public void normalize() {
    CGAL_KernelJNI.Vector_3_normalize(swigCPtr, this);
  }

}
