package configuration.enumerations;

public enum AerodynamicAndStabilityPlotEnum {

 WING_CL_CURVE_CLEAN,
 WING_CL_CURVE_HIGH_LIFT,
 HTAIL_CL_CURVE_CLEAN,
 HTAIL_CL_CURVE_ELEVATOR,
 WING_POLAR_CURVE_CLEAN,
 WING_POLAR_CURVE_HIGHLIFT,
 HTAIL_POLAR_CURVE_CLEAN,
 WING_CM_QUARTER_CHORD,
 WING_CM_AERODYNAMIC_CENTER,
 HTAIL_CM_QUARTER_CHORD,
 HTAIL_CM_AERODYNAMIC_CENTER,
 FUSELAGE_CM_PLOT,
 PROPULSIVE_SYSTEM_CM_DIRECT_EFFECTS,
 PROPULSIVE_SYSTEM_CM_NON_DIRECT_EFFECTS,
 AIRCRAFT_CM_VS_ALPHA_BODY_COMPONENTS,
 AIRCRAFT_CM_VS_ALPHA_BODY,
 AIRCRAFT_CM_VS_ALPHA_BODY_DELTAE,
 AIRCRAFT_CL_VS_ALPHA_BODY_DELTAE,
 AIRCRAFT_CM_VS_CL_DELTAE,
 DOWNWASH_ANGLE,
 DOWNWASH_GRADIENT,
 DELTA_E_EQUILIBRIUM,
 NEUTRAL_POINT
	// TODO : ADD OTHER IF NEEDED
	
}
