package configuration.enumerations;

public enum CostsDerivedDataEnum {

	AIRCRAFT_PRICE,
	UTILIZATION,
	LANDING_CHARGES,
	NAVIGATION_CHARGES,
	GROUND_HANDLING_CHARGES,
	NOISE_CHARGES,
	EMISSION_NOx_CHARGES,
	EMISSION_CO_CHARGES,
	EMISSION_HC_CHARGES,
	ENGINE_PRICE;
	
}
