package configuration.enumerations;

public enum HighLiftDeviceEffectEnum {

	DELTA_Cl0_FLAP_LIST,
	DELTA_CL0_FLAP_LIST,
	DELTA_Cl_MAX_FLAP_LIST,
	DELTA_CL_MAX_FLAP_LIST,
	DELTA_Cl_MAX_SLAT_LIST,
	DELTA_CL_MAX_SLAT_LIST,
	DELTA_CD_LIST,
	DELTA_CM_c4_LIST,
	DELTA_Cl0_FLAP,
	DELTA_CL0_FLAP,
	DELTA_Cl_MAX_FLAP,
	DELTA_CL_MAX_FLAP,
	DELTA_Cl_MAX_SLAT,
	DELTA_CL_MAX_SLAT,
	DELTA_CD,
	DELTA_CM_c4,
	CL_ALPHA_HIGH_LIFT,
	CL_ALPHA_HIGH_LIFT_LIST
	
}
