package configuration.enumerations;

public enum PerformancePlotEnum {

	TAKE_OFF_SIMULATIONS,
	BALANCED_FIELD_LENGTH,
	RATE_OF_CLIMB_CURVES,
	CLIMB_ANGLE_CURVES,
	MAX_RATE_OF_CLIMB_ENVELOPE,
	THRUST_DRAG_CURVES_CLIMB,
	THRUST_DRAG_CURVES_CRUISE,
	POWER_NEEDED_AND_AVAILABLE_CURVES_CLIMB,
	POWER_NEEDED_AND_AVAILABLE_CURVES_CRUISE,
	EFFICIENCY_CURVES,
	CRUISE_GRID_CHART,
	CRUISE_FLIGHT_ENVELOPE,
	LANDING_SIMULATIONS,
	PAYLOAD_RANGE,
	FLIGHT_MANEUVERING_AND_GUST_DIAGRAM;
	
	
}
