package configuration.enumerations;

public enum PerformancePlotEnum {

	TAKE_OFF_SIMULATIONS,
	BALANCED_FIELD_LENGTH,
	THRUST_DRAG_CURVES,
	EFFICIENCY_CURVES,
	SFC_CURVE,
	CRUISE_GRID_CHART,
	CRUISE_FLIGHT_ENVELOPE,
	LANDING_SIMULATIONS,
	PAYLOAD_RANGE,
	FLIGHT_MANEUVERING_AND_GUST_DIAGRAM;
	
	// TODO : ADD OTHER IF NEEDED
	
}
