/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Triangulation_2;

public class Ref_Locate_type_2 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Ref_Locate_type_2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Ref_Locate_type_2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_Triangulation_2JNI.delete_Ref_Locate_type_2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Ref_Locate_type_2() {
    this(CGAL_Triangulation_2JNI.new_Ref_Locate_type_2__SWIG_0(), true);
  }

  public Ref_Locate_type_2(Locate_type k) {
    this(CGAL_Triangulation_2JNI.new_Ref_Locate_type_2__SWIG_1(k.swigValue()), true);
  }

  public void set(Locate_type t) {
    CGAL_Triangulation_2JNI.Ref_Locate_type_2_set(swigCPtr, this, t.swigValue());
  }

  public Locate_type object() {
    return Locate_type.swigToEnum(CGAL_Triangulation_2JNI.Ref_Locate_type_2_object(swigCPtr, this));
  }

  public Ref_Locate_type_2 clone() {
    return new Ref_Locate_type_2(CGAL_Triangulation_2JNI.Ref_Locate_type_2_clone__SWIG_0(swigCPtr, this), true);
  }

  public void clone(Ref_Locate_type_2 other) {
    CGAL_Triangulation_2JNI.Ref_Locate_type_2_clone__SWIG_1(swigCPtr, this, Ref_Locate_type_2.getCPtr(other), other);
  }

}
