/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Triangulation_2;

public class Triangulation_2_Face_handle {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Triangulation_2_Face_handle(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Triangulation_2_Face_handle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_Triangulation_2JNI.delete_Triangulation_2_Face_handle(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Triangulation_2_Face_handle() {
    this(CGAL_Triangulation_2JNI.new_Triangulation_2_Face_handle(), true);
  }

  public int dimension() {
    return CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_dimension(swigCPtr, this);
  }

  public Triangulation_2_Vertex_handle vertex(int c) {
    return new Triangulation_2_Vertex_handle(CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_vertex__SWIG_0(swigCPtr, this, c), true);
  }

  public void vertex(int c, Triangulation_2_Vertex_handle ret) {
    CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_vertex__SWIG_1(swigCPtr, this, c, Triangulation_2_Vertex_handle.getCPtr(ret), ret);
  }

  public boolean has_vertex(Triangulation_2_Vertex_handle c) {
    return CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_has_vertex(swigCPtr, this, Triangulation_2_Vertex_handle.getCPtr(c), c);
  }

  public int index(Triangulation_2_Vertex_handle c) {
    return CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_index__SWIG_0(swigCPtr, this, Triangulation_2_Vertex_handle.getCPtr(c), c);
  }

  public Triangulation_2_Face_handle neighbor(int c) {
    return new Triangulation_2_Face_handle(CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_neighbor__SWIG_0(swigCPtr, this, c), true);
  }

  public void neighbor(int c, Triangulation_2_Face_handle ret) {
    CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_neighbor__SWIG_1(swigCPtr, this, c, Triangulation_2_Face_handle.getCPtr(ret), ret);
  }

  public boolean has_neighbor(Triangulation_2_Face_handle c) {
    return CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_has_neighbor(swigCPtr, this, Triangulation_2_Face_handle.getCPtr(c), c);
  }

  public int index(Triangulation_2_Face_handle c) {
    return CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_index__SWIG_1(swigCPtr, this, Triangulation_2_Face_handle.getCPtr(c), c);
  }

  public void set_vertex(int c1, Triangulation_2_Vertex_handle c2) {
    CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_set_vertex(swigCPtr, this, c1, Triangulation_2_Vertex_handle.getCPtr(c2), c2);
  }

  public void set_vertices() {
    CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_set_vertices__SWIG_0(swigCPtr, this);
  }

  public void set_vertices(Triangulation_2_Vertex_handle c1, Triangulation_2_Vertex_handle c2, Triangulation_2_Vertex_handle c3) {
    CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_set_vertices__SWIG_1(swigCPtr, this, Triangulation_2_Vertex_handle.getCPtr(c1), c1, Triangulation_2_Vertex_handle.getCPtr(c2), c2, Triangulation_2_Vertex_handle.getCPtr(c3), c3);
  }

  public void set_neighbor(int c1, Triangulation_2_Face_handle c2) {
    CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_set_neighbor(swigCPtr, this, c1, Triangulation_2_Face_handle.getCPtr(c2), c2);
  }

  public void set_neighbors() {
    CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_set_neighbors__SWIG_0(swigCPtr, this);
  }

  public void set_neighbors(Triangulation_2_Face_handle c1, Triangulation_2_Face_handle c2, Triangulation_2_Face_handle c3) {
    CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_set_neighbors__SWIG_1(swigCPtr, this, Triangulation_2_Face_handle.getCPtr(c1), c1, Triangulation_2_Face_handle.getCPtr(c2), c2, Triangulation_2_Face_handle.getCPtr(c3), c3);
  }

  public void reorient() {
    CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_reorient(swigCPtr, this);
  }

  public void ccw_permute() {
    CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_ccw_permute(swigCPtr, this);
  }

  public void cw_permute() {
    CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_cw_permute(swigCPtr, this);
  }

  public boolean is_valid() {
    return CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_is_valid__SWIG_0(swigCPtr, this);
  }

  public boolean is_valid(boolean c) {
    return CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_is_valid__SWIG_1(swigCPtr, this, c);
  }

  public boolean lt(Triangulation_2_Face_handle p) {
    return CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_lt(swigCPtr, this, Triangulation_2_Face_handle.getCPtr(p), p);
  }

  public boolean gt(Triangulation_2_Face_handle p) {
    return CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_gt(swigCPtr, this, Triangulation_2_Face_handle.getCPtr(p), p);
  }

  public boolean le(Triangulation_2_Face_handle p) {
    return CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_le(swigCPtr, this, Triangulation_2_Face_handle.getCPtr(p), p);
  }

  public boolean ge(Triangulation_2_Face_handle p) {
    return CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_ge(swigCPtr, this, Triangulation_2_Face_handle.getCPtr(p), p);
  }

  public boolean equals(Triangulation_2_Face_handle p) {
    return CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_equals(swigCPtr, this, Triangulation_2_Face_handle.getCPtr(p), p);
  }

  public boolean not_equals(Triangulation_2_Face_handle p) {
    return CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_not_equals(swigCPtr, this, Triangulation_2_Face_handle.getCPtr(p), p);
  }

  public int hashCode() {
    return CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_hashCode(swigCPtr, this);
  }

  public Triangulation_2_Face_handle clone() {
    return new Triangulation_2_Face_handle(CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_clone__SWIG_0(swigCPtr, this), true);
  }

  public void clone(Triangulation_2_Face_handle other) {
    CGAL_Triangulation_2JNI.Triangulation_2_Face_handle_clone__SWIG_1(swigCPtr, this, Triangulation_2_Face_handle.getCPtr(other), other);
  }

}
