/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Surface_mesher;

public class Gray_level_image_3 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Gray_level_image_3(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Gray_level_image_3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_Surface_mesherJNI.delete_Gray_level_image_3(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Gray_level_image_3(String s, double iso_value) {
    this(CGAL_Surface_mesherJNI.new_Gray_level_image_3(s, iso_value), true);
  }

}
