clear all, close all, clc

%% load data file generated by Grabit
% https://it.mathworks.com/matlabcentral/fileexchange/7173-grabit

fileBaseNames = {'B_vs_h_frac_overline_c_C_L_WB_0' , 'B_vs_h_frac_overline_c_C_L_WB_02' , 'B_vs_h_frac_overline_c_C_L_WB_04' , 'B_vs_h_frac_overline_c_C_L_WB_06' , 'B_vs_h_frac_overline_c_C_L_WB_08' , 'B_vs_h_frac_overline_c_C_L_WB_1' , 'B_vs_h_frac_overline_c_C_L_WB_12' , 'B_vs_h_frac_overline_c_C_L_WB_14' , 'B_vs_h_frac_overline_c_C_L_WB_16'};
nPoints = 25;

xx = linspace(0.2, 2.4, nPoints);

for kFile = 1:length(fileBaseNames)
    
%     fileName = sprintf('%s.mat',fileBaseNames{kFile});
    s = load(fileBaseNames{kFile}, '-mat');

    % Allocate imported array to column variable names
    
    x{kFile} = s.(fileBaseNames{kFile})(:, 1);
    x{kFile}(end) = 2.4;
    
    y{kFile} = s.(fileBaseNames{kFile})(:, 2);
    %% Smoothing
    pp(kFile) = csaps(x{kFile}, y{kFile}, 0.999999);
    c{kFile} = ppval(pp(kFile), xx');
    data(:,kFile) = c{kFile};

    plot (xx', data(:,kFile), '-*');
    hold on
end
xlabel('$\frac{h_{{c_r}/4}}{c_r}$','interpreter','latex'); 
ylabel('$\frac{L}{L_0}-1$','interpreter','latex');
set(get(gca,'ylabel'),'rotation',0)

title('Parameter accounting for ground effect on lift due to trailing vortices');
axis([0 2.4 -0.5 .4]);
legend('0','5','10', '15','20','22' ,'24', '36');


%% preparing output to HDF

CL_2_2pi_cos_2_Gamma_c4 = [0 5 10 15 20 22 24 36]';
h_cr_4_cr = xx';

 
%columns --> curves
 
hdfFileName = 'Delta_alpha_CL_Ground_Effect_L_L0_minus1_vs_h_cr_4_cr';

if ( exist(hdfFileName, 'file') )
    fprintf('file %s exists, deleting and creating a new one\n', hdfFileName);
    delete(hdfFileName)
else
    fprintf('Creating new file %s\n', hdfFileName);
end

h5create(hdfFileName, '/(Delta_alpha_CL_Ground_Effect)_L_L0_minus1_vs_h_cr_4_cr/data', size(data'));
h5write(hdfFileName, '/(Delta_alpha_CL_Ground_Effect)_L_L0_minus1_vs_h_cr_4_cr/data', data');

h5create(hdfFileName, '/(Delta_alpha_CL_Ground_Effect)_L_L0_minus1_vs_h_cr_4_cr/var_0', size(CL_2_2pi_cos_2_Gamma_c4'));
h5write(hdfFileName, '/(Delta_alpha_CL_Ground_Effect)_L_L0_minus1_vs_h_cr_4_cr/var_0', CL_2_2pi_cos_2_Gamma_c4');

h5create(hdfFileName, '/(Delta_alpha_CL_Ground_Effect)_L_L0_minus1_vs_h_cr_4_cr/var_1', size(h_cr_4_cr'));
h5write(hdfFileName, '/(Delta_alpha_CL_Ground_Effect)_L_L0_minus1_vs_h_cr_4_cr/var_1', h_cr_4_cr');

