/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Mesh_3;

public class CGAL_Mesh_3 {
  public static Mesh_optimization_return_code exude_mesh_3(Mesh_3_Complex_3_in_triangulation_3 c3t3, double time_limit, double sliver_bound) {
    return Mesh_optimization_return_code.swigToEnum(CGAL_Mesh_3JNI.exude_mesh_3(Mesh_3_Complex_3_in_triangulation_3.getCPtr(c3t3), c3t3, time_limit, sliver_bound));
  }

  public static Mesh_optimization_return_code perturb_mesh_3(Mesh_3_Complex_3_in_triangulation_3 c3t3, Polyhedral_mesh_domain_3 domain, double time_limit, double sliver_bound) {
    return Mesh_optimization_return_code.swigToEnum(CGAL_Mesh_3JNI.perturb_mesh_3(Mesh_3_Complex_3_in_triangulation_3.getCPtr(c3t3), c3t3, Polyhedral_mesh_domain_3.getCPtr(domain), domain, time_limit, sliver_bound));
  }

  public static Mesh_optimization_return_code lloyd_optimize_mesh_3(Mesh_3_Complex_3_in_triangulation_3 c3t3, Polyhedral_mesh_domain_3 domain, double time_limit, int max_iteration_number, double convergence, double freeze_bound) {
    return Mesh_optimization_return_code.swigToEnum(CGAL_Mesh_3JNI.lloyd_optimize_mesh_3(Mesh_3_Complex_3_in_triangulation_3.getCPtr(c3t3), c3t3, Polyhedral_mesh_domain_3.getCPtr(domain), domain, time_limit, max_iteration_number, convergence, freeze_bound));
  }

  public static Mesh_optimization_return_code odt_optimize_mesh_3(Mesh_3_Complex_3_in_triangulation_3 c3t3, Polyhedral_mesh_domain_3 domain, double time_limit, long max_iteration_number, double convergence, double freeze_bound) {
    return Mesh_optimization_return_code.swigToEnum(CGAL_Mesh_3JNI.odt_optimize_mesh_3(Mesh_3_Complex_3_in_triangulation_3.getCPtr(c3t3), c3t3, Polyhedral_mesh_domain_3.getCPtr(domain), domain, time_limit, max_iteration_number, convergence, freeze_bound));
  }

  public static Mesh_3_Complex_3_in_triangulation_3 make_mesh_3(Polyhedral_mesh_domain_3 domain, Default_mesh_criteria criteria, Mesh_3_parameters parameters) {
    return new Mesh_3_Complex_3_in_triangulation_3(CGAL_Mesh_3JNI.make_mesh_3__SWIG_0(Polyhedral_mesh_domain_3.getCPtr(domain), domain, Default_mesh_criteria.getCPtr(criteria), criteria, Mesh_3_parameters.getCPtr(parameters), parameters), true);
  }

  public static void refine_mesh_3(Mesh_3_Complex_3_in_triangulation_3 c3t3, Polyhedral_mesh_domain_3 domain, Default_mesh_criteria criteria, Mesh_3_parameters parameters) {
    CGAL_Mesh_3JNI.refine_mesh_3__SWIG_0(Mesh_3_Complex_3_in_triangulation_3.getCPtr(c3t3), c3t3, Polyhedral_mesh_domain_3.getCPtr(domain), domain, Default_mesh_criteria.getCPtr(criteria), criteria, Mesh_3_parameters.getCPtr(parameters), parameters);
  }

  public static Mesh_3_Complex_3_in_triangulation_3 make_mesh_3(Polyhedral_mesh_domain_3 domain, User_mesh_criteria criteria, Mesh_3_parameters parameters) {
    return new Mesh_3_Complex_3_in_triangulation_3(CGAL_Mesh_3JNI.make_mesh_3__SWIG_1(Polyhedral_mesh_domain_3.getCPtr(domain), domain, User_mesh_criteria.getCPtr(criteria), criteria, Mesh_3_parameters.getCPtr(parameters), parameters), true);
  }

  public static void refine_mesh_3(Mesh_3_Complex_3_in_triangulation_3 c3t3, Polyhedral_mesh_domain_3 domain, User_mesh_criteria criteria, Mesh_3_parameters parameters) {
    CGAL_Mesh_3JNI.refine_mesh_3__SWIG_1(Mesh_3_Complex_3_in_triangulation_3.getCPtr(c3t3), c3t3, Polyhedral_mesh_domain_3.getCPtr(domain), domain, User_mesh_criteria.getCPtr(criteria), criteria, Mesh_3_parameters.getCPtr(parameters), parameters);
  }

}
