/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Mesh_3;

public class Default_mesh_criteria {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Default_mesh_criteria(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Default_mesh_criteria obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_Mesh_3JNI.delete_Default_mesh_criteria(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Default_mesh_criteria() {
    this(CGAL_Mesh_3JNI.new_Default_mesh_criteria(), true);
  }

  public Default_mesh_criteria edge_size(double v) {
    return new Default_mesh_criteria(CGAL_Mesh_3JNI.Default_mesh_criteria_edge_size(swigCPtr, this, v), false);
  }

  public Default_mesh_criteria facet_angle(double v) {
    return new Default_mesh_criteria(CGAL_Mesh_3JNI.Default_mesh_criteria_facet_angle(swigCPtr, this, v), false);
  }

  public Default_mesh_criteria facet_size(double v) {
    return new Default_mesh_criteria(CGAL_Mesh_3JNI.Default_mesh_criteria_facet_size(swigCPtr, this, v), false);
  }

  public Default_mesh_criteria facet_distance(double v) {
    return new Default_mesh_criteria(CGAL_Mesh_3JNI.Default_mesh_criteria_facet_distance(swigCPtr, this, v), false);
  }

  public Default_mesh_criteria facet_topology(Mesh_facet_topology v) {
    return new Default_mesh_criteria(CGAL_Mesh_3JNI.Default_mesh_criteria_facet_topology(swigCPtr, this, v.swigValue()), false);
  }

  public Default_mesh_criteria cell_radius_edge_ratio(double v) {
    return new Default_mesh_criteria(CGAL_Mesh_3JNI.Default_mesh_criteria_cell_radius_edge_ratio(swigCPtr, this, v), false);
  }

  public Default_mesh_criteria cell_size(double v) {
    return new Default_mesh_criteria(CGAL_Mesh_3JNI.Default_mesh_criteria_cell_size(swigCPtr, this, v), false);
  }

  public Default_mesh_criteria clone() {
    return new Default_mesh_criteria(CGAL_Mesh_3JNI.Default_mesh_criteria_clone__SWIG_0(swigCPtr, this), true);
  }

  public void clone(Default_mesh_criteria other) {
    CGAL_Mesh_3JNI.Default_mesh_criteria_clone__SWIG_1(swigCPtr, this, Default_mesh_criteria.getCPtr(other), other);
  }

}
