/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Mesh_3;

public class Mesh_3_Index {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Mesh_3_Index(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Mesh_3_Index obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_Mesh_3JNI.delete_Mesh_3_Index(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Mesh_3_Index() {
    this(CGAL_Mesh_3JNI.new_Mesh_3_Index__SWIG_0(), true);
  }

  public Mesh_3_Index(int t1) {
    this(CGAL_Mesh_3JNI.new_Mesh_3_Index__SWIG_1(t1), true);
  }

  public Mesh_3_Index(Mesh_3_Surface_index t2) {
    this(CGAL_Mesh_3JNI.new_Mesh_3_Index__SWIG_2(Mesh_3_Surface_index.getCPtr(t2), t2), true);
  }

  public boolean is_of_first_type() {
    return CGAL_Mesh_3JNI.Mesh_3_Index_is_of_first_type(swigCPtr, this);
  }

  public boolean is_of_second_type() {
    return CGAL_Mesh_3JNI.Mesh_3_Index_is_of_second_type(swigCPtr, this);
  }

  public int get_first() {
    return CGAL_Mesh_3JNI.Mesh_3_Index_get_first(swigCPtr, this);
  }

  public Mesh_3_Surface_index get_second() {
    return new Mesh_3_Surface_index(CGAL_Mesh_3JNI.Mesh_3_Index_get_second(swigCPtr, this), true);
  }

  public Mesh_3_Index clone() {
    return new Mesh_3_Index(CGAL_Mesh_3JNI.Mesh_3_Index_clone__SWIG_0(swigCPtr, this), true);
  }

  public void clone(Mesh_3_Index other) {
    CGAL_Mesh_3JNI.Mesh_3_Index_clone__SWIG_1(swigCPtr, this, Mesh_3_Index.getCPtr(other), other);
  }

}
