clc; close all; clear all;

%% Import data
clmax_CLMax_dy1p4 = importdata('clmaxCLmaxdy1p4.mat');
clmax_CLMax_dy1p6 = importdata('clmaxCLmaxdy1p6.mat');
clmax_CLMax_dy1p8 = importdata('clmaxCLmaxdy1p8.mat');
clmax_CLMax_dy2 = importdata('clmaxCLmaxdy2.mat');
clmax_CLMax_dy2p2 = importdata('clmaxCLmaxdy2p2.mat');
clmax_CLMax_dy2p4 = importdata('clmaxCLmaxdy2p4.mat');
clmax_CLMax_dy2p5 = importdata('clmaxCLmaxdy2p5.mat');

nPoints = 50;
lambdaLEVector = transpose(linspace(0, 60, nPoints));

%% Clmax/CLmax dy=1.4
smoothingParameter = 0.999999;
clmax_CLMax_dy1p4_SplineStatic = csaps( ...
    clmax_CLMax_dy1p4(:,1), ...
    clmax_CLMax_dy1p4(:,2), ...
    smoothingParameter ...
    );

clmax_CLMax_dy1p4_Static = ppval( ...
    clmax_CLMax_dy1p4_SplineStatic, ...
    lambdaLEVector ...
    );

%% Clmax/CLmax dy=1.6
smoothingParameter = 0.999999;
clmax_CLMax_dy1p6_SplineStatic = csaps( ...
    clmax_CLMax_dy1p6(:,1), ...
    clmax_CLMax_dy1p6(:,2), ...
    smoothingParameter ...
    );

clmax_CLMax_dy1p6_Static = ppval( ...
    clmax_CLMax_dy1p6_SplineStatic, ...
    lambdaLEVector ...
    );

%% Clmax/CLmax dy=1.8
smoothingParameter = 0.999999;
clmax_CLMax_dy1p8_SplineStatic = csaps( ...
    clmax_CLMax_dy1p8(:,1), ...
    clmax_CLMax_dy1p8(:,2), ...
    smoothingParameter ...
    );

clmax_CLMax_dy1p8_Static = ppval( ...
    clmax_CLMax_dy1p8_SplineStatic, ...
    lambdaLEVector ...
    );

%% Clmax/CLmax dy=2
smoothingParameter = 0.999999;
clmax_CLMax_dy2_SplineStatic = csaps( ...
    clmax_CLMax_dy2(:,1), ...
    clmax_CLMax_dy2(:,2), ...
    smoothingParameter ...
    );

clmax_CLMax_dy2_Static = ppval( ...
    clmax_CLMax_dy2_SplineStatic, ...
    lambdaLEVector ...
    );

%% Clmax/CLmax dy=2.2
smoothingParameter = 0.999999;
clmax_CLMax_dy2p2_SplineStatic = csaps( ...
    clmax_CLMax_dy2p2(:,1), ...
    clmax_CLMax_dy2p2(:,2), ...
    smoothingParameter ...
    );

clmax_CLMax_dy2p2_Static = ppval( ...
    clmax_CLMax_dy2p2_SplineStatic, ...
    lambdaLEVector ...
    );

%% Clmax/CLmax dy=2.4
smoothingParameter = 0.999999;
clmax_CLMax_dy2p4_SplineStatic = csaps( ...
    clmax_CLMax_dy2p4(:,1), ...
    clmax_CLMax_dy2p4(:,2), ...
    smoothingParameter ...
    );

clmax_CLMax_dy2p4_Static = ppval( ...
    clmax_CLMax_dy2p4_SplineStatic, ...
    lambdaLEVector ...
    );

%% Clmax/CLmax dy=2.5
smoothingParameter = 0.999999;
clmax_CLMax_dy2p5_SplineStatic = csaps( ...
    clmax_CLMax_dy2p5(:,1), ...
    clmax_CLMax_dy2p5(:,2), ...
    smoothingParameter ...
    );

clmax_CLMax_dy2p5_Static = ppval( ...
    clmax_CLMax_dy2p5_SplineStatic, ...
    lambdaLEVector ...
    );

%% Plots
figure(1)
plot ( ...
    lambdaLEVector, clmax_CLMax_dy1p4_Static, 'b-.' ... , ...
 );

hold on;

plot ( ...
    lambdaLEVector, clmax_CLMax_dy1p6_Static, 'b-o' ... , ...
 );

hold on;

plot ( ...
    lambdaLEVector, clmax_CLMax_dy1p8_Static, 'b-*' ... , ...
 );

hold on;

plot ( ...
    lambdaLEVector, clmax_CLMax_dy2_Static, 'b-^' ... , ...
 );

hold on;

plot ( ...
    lambdaLEVector, clmax_CLMax_dy2p2_Static, 'b-x' ... , ...
 );

hold on;

plot ( ...
    lambdaLEVector, clmax_CLMax_dy2p4_Static, 'b-v' ... , ...
 );

hold on;

plot ( ...
    lambdaLEVector, clmax_CLMax_dy2p5_Static, 'b-' ... , ...
 );

xlabel('\Lambda_{LE}'); ylabel('C_{l,max}/C_{L,max}');
 title('C_{l,max}/C_{L,max} variation with \Lambda_{LE} and \Deltay');
   legend('\Deltay <= 1.6','\Deltay = 1.8','\Deltay = 2.0','\Deltay = 2.2', ...
            '\Deltay = 2.4','\Deltay => 2.5');
 
 axis([0 60 0.4 1.6]);
 grid on;
 %% preparing output to HDF 

% dy
dyVector = [ ...
    1.4;1.6;1.8;2.0;2.2;2.4;2.5 ...
    ];
 
%columns --> curves
myData = [ ...
    clmax_CLMax_dy1p4_Static,...
    clmax_CLMax_dy1p6_Static, ... 
    clmax_CLMax_dy1p8_Static, ... 
    clmax_CLMax_dy2_Static, ...
    clmax_CLMax_dy2p2_Static, ...
    clmax_CLMax_dy2p4_Static, ...
    clmax_CLMax_dy2p5_Static]; 

hdfFileName = 'Clmax_CLmax_vs_LambdaLE_vs_dy.h5';

if ( exist(hdfFileName, 'file') )
    fprintf('file %s exists, deleting and creating a new one\n', hdfFileName);
    delete(hdfFileName)
else
    fprintf('Creating new file %s\n', hdfFileName);
end

% Dataset: data
h5create(hdfFileName, '/Clmax_CLmax_vs_LambdaLE_vs_dy/data', size(myData'));
h5write(hdfFileName, '/Clmax_CLmax_vs_LambdaLE_vs_dy/data', myData');

% Dataset: var_1
h5create(hdfFileName, '/Clmax_CLmax_vs_LambdaLE_vs_dy/var_1', size(lambdaLEVector'));
h5write(hdfFileName, '/Clmax_CLmax_vs_LambdaLE_vs_dy/var_1', lambdaLEVector');

% Dataset: var_0
h5create(hdfFileName, '/Clmax_CLmax_vs_LambdaLE_vs_dy/var_0', size(dyVector'));
h5write(hdfFileName, '/Clmax_CLmax_vs_LambdaLE_vs_dy/var_0', dyVector');
