package aircraft.components.liftingSurface.creator;

public class SpoilerCreator {

	/* TODO : SEE IF THE SPOLIER HAVE TO BE PUT INSIDE THE WING SINCE 
	 *		  THEY CAN BE MOUNTED ALSO ON THE FUSELAGE. */
	
	/* TODO : CHOOSE WHICH IS THE BEST WAY TO CALCULATE THE SPOILER 
	 *        dCD0 FROM APPENDIX B OF THESIS TRIFARI. 
	 */
	
	/* TODO : DECIDE FROM THE PREVIOUS POINT WHICH ARE THE MAIN 
	 * 		  PARAMETERS OF THE SPOILER SURFACE.
	 */
	
}
