clc; close all; clear all;

%% Import data
kOmegaA4T0p3 = importdata('kOmegaA4T0p3.mat');
kOmegaA4T0p4 = importdata('kOmegaA4T0p4.mat');
kOmegaA4T0p5 = importdata('kOmegaA4T0p5.mat');
kOmegaA4T0p6 = importdata('kOmegaA4T0p6.mat');
kOmegaA4T0p7 = importdata('kOmegaA4T0p7.mat');
kOmegaA4T0p8 = importdata('kOmegaA4T0p8.mat');
kOmegaA4T0p9 = importdata('kOmegaA4T0p9.mat');
kOmegaA4T1 = importdata('kOmegaA4T1.mat');

kOmegaA8T0p3 = importdata('kOmegaA8T0p3.mat');
kOmegaA8T0p4 = importdata('kOmegaA8T0p4.mat');
kOmegaA8T0p5 = importdata('kOmegaA8T0p5.mat');
kOmegaA8T0p6 = importdata('kOmegaA8T0p6.mat');
kOmegaA8T0p7 = importdata('kOmegaA8T0p7.mat');
kOmegaA8T0p8 = importdata('kOmegaA8T0p8.mat');
kOmegaA8T0p9 = importdata('kOmegaA8T0p9.mat');
kOmegaA8T1 = importdata('kOmegaA8T1.mat');

kOmegaA20T0p3 = importdata('kOmegaA20T0p3.mat');
kOmegaA20T0p4 = importdata('kOmegaA20T0p4.mat');
kOmegaA20T0p5 = importdata('kOmegaA20T0p5.mat');
kOmegaA20T0p6 = importdata('kOmegaA20T0p6.mat');
kOmegaA20T0p7 = importdata('kOmegaA20T0p7.mat');
kOmegaA20T0p8 = importdata('kOmegaA20T0p8.mat');
kOmegaA20T0p9 = importdata('kOmegaA20T0p9.mat');
kOmegaA20T1 = importdata('kOmegaA20T1.mat');

nPoints = 50;
CLalphaOmegaFracClmax = transpose(linspace(0, 0.5, nPoints));

%% taperRatio = 0.3 AR = 4
smoothingParameter = 0.999999;
kOmegaA4T0p3_SplineStatic = csaps( ...
    kOmegaA4T0p3(:,1), ...
    kOmegaA4T0p3(:,2), ...
    smoothingParameter ...
    );

kOmegaA4T0p3_Static = ppval( ...
    kOmegaA4T0p3_SplineStatic, ...
    CLalphaOmegaFracClmax ...
    );

%% taperRatio = 0.4 AR = 4
smoothingParameter = 0.999999;
kOmegaA4T0p4_SplineStatic = csaps( ...
    kOmegaA4T0p4(:,1), ...
    kOmegaA4T0p4(:,2), ...
    smoothingParameter ...
    );

kOmegaA4T0p4_Static = ppval( ...
    kOmegaA4T0p4_SplineStatic, ...
    CLalphaOmegaFracClmax ...
    );

%% taperRatio = 0.5 AR = 4
smoothingParameter = 0.999999;
kOmegaA4T0p5_SplineStatic = csaps( ...
    kOmegaA4T0p5(:,1), ...
    kOmegaA4T0p5(:,2), ...
    smoothingParameter ...
    );

kOmegaA4T0p5_Static = ppval( ...
    kOmegaA4T0p5_SplineStatic, ...
    CLalphaOmegaFracClmax ...
    );

%% taperRatio = 0.6 AR = 4
smoothingParameter = 0.999999;
kOmegaA4T0p6_SplineStatic = csaps( ...
    kOmegaA4T0p6(:,1), ...
    kOmegaA4T0p6(:,2), ...
    smoothingParameter ...
    );

kOmegaA4T0p6_Static = ppval( ...
    kOmegaA4T0p6_SplineStatic, ...
    CLalphaOmegaFracClmax ...
    );

%% taperRatio = 0.7 AR = 4
smoothingParameter = 0.999999;
kOmegaA4T0p7_SplineStatic = csaps( ...
    kOmegaA4T0p7(:,1), ...
    kOmegaA4T0p7(:,2), ...
    smoothingParameter ...
    );

kOmegaA4T0p7_Static = ppval( ...
    kOmegaA4T0p7_SplineStatic, ...
    CLalphaOmegaFracClmax ...
    );

%% taperRatio = 0.8 AR = 4
smoothingParameter = 0.999999;
kOmegaA4T0p8_SplineStatic = csaps( ...
    kOmegaA4T0p8(:,1), ...
    kOmegaA4T0p8(:,2), ...
    smoothingParameter ...
    );

kOmegaA4T0p8_Static = ppval( ...
    kOmegaA4T0p8_SplineStatic, ...
    CLalphaOmegaFracClmax ...
    );

%% taperRatio = 0.9 AR = 4
smoothingParameter = 0.999999;
kOmegaA4T0p9_SplineStatic = csaps( ...
    kOmegaA4T0p9(:,1), ...
    kOmegaA4T0p9(:,2), ...
    smoothingParameter ...
    );

kOmegaA4T0p9_Static = ppval( ...
    kOmegaA4T0p9_SplineStatic, ...
    CLalphaOmegaFracClmax ...
    );

%% taperRatio = 1 AR = 4
smoothingParameter = 0.999999;
kOmegaA4T1_SplineStatic = csaps( ...
    kOmegaA4T1(:,1), ...
    kOmegaA4T1(:,2), ...
    smoothingParameter ...
    );

kOmegaA4T1_Static = ppval( ...
    kOmegaA4T1_SplineStatic, ...
    CLalphaOmegaFracClmax ...
    );

%% taperRatio = 0.3 AR = 8
smoothingParameter = 0.999999;
kOmegaA8T0p3_SplineStatic = csaps( ...
    kOmegaA8T0p3(:,1), ...
    kOmegaA8T0p3(:,2), ...
    smoothingParameter ...
    );

kOmegaA8T0p3_Static = ppval( ...
    kOmegaA8T0p3_SplineStatic, ...
    CLalphaOmegaFracClmax ...
    );

%% taperRatio = 0.4 AR = 8
smoothingParameter = 0.999999;
kOmegaA8T0p4_SplineStatic = csaps( ...
    kOmegaA8T0p4(:,1), ...
    kOmegaA8T0p4(:,2), ...
    smoothingParameter ...
    );

kOmegaA8T0p4_Static = ppval( ...
    kOmegaA8T0p4_SplineStatic, ...
    CLalphaOmegaFracClmax ...
    );

%% taperRatio = 0.5 AR = 8
smoothingParameter = 0.999999;
kOmegaA8T0p5_SplineStatic = csaps( ...
    kOmegaA8T0p5(:,1), ...
    kOmegaA8T0p5(:,2), ...
    smoothingParameter ...
    );

kOmegaA8T0p5_Static = ppval( ...
    kOmegaA8T0p5_SplineStatic, ...
    CLalphaOmegaFracClmax ...
    );

%% taperRatio = 0.6 AR = 8
smoothingParameter = 0.999999;
kOmegaA8T0p6_SplineStatic = csaps( ...
    kOmegaA8T0p6(:,1), ...
    kOmegaA8T0p6(:,2), ...
    smoothingParameter ...
    );

kOmegaA8T0p6_Static = ppval( ...
    kOmegaA8T0p6_SplineStatic, ...
    CLalphaOmegaFracClmax ...
    );

%% taperRatio = 0.7 AR = 8
smoothingParameter = 0.999999;
kOmegaA8T0p7_SplineStatic = csaps( ...
    kOmegaA8T0p7(:,1), ...
    kOmegaA8T0p7(:,2), ...
    smoothingParameter ...
    );

kOmegaA8T0p7_Static = ppval( ...
    kOmegaA8T0p7_SplineStatic, ...
    CLalphaOmegaFracClmax ...
    );

%% taperRatio = 0.8 AR = 8
smoothingParameter = 0.999999;
kOmegaA8T0p8_SplineStatic = csaps( ...
    kOmegaA8T0p8(:,1), ...
    kOmegaA8T0p8(:,2), ...
    smoothingParameter ...
    );

kOmegaA8T0p8_Static = ppval( ...
    kOmegaA8T0p8_SplineStatic, ...
    CLalphaOmegaFracClmax ...
    );

%% taperRatio = 0.9 AR = 8
smoothingParameter = 0.999999;
kOmegaA8T0p9_SplineStatic = csaps( ...
    kOmegaA8T0p9(:,1), ...
    kOmegaA8T0p9(:,2), ...
    smoothingParameter ...
    );

kOmegaA8T0p9_Static = ppval( ...
    kOmegaA8T0p9_SplineStatic, ...
    CLalphaOmegaFracClmax ...
    );

%% taperRatio = 1 AR = 8
smoothingParameter = 0.999999;
kOmegaA8T1_SplineStatic = csaps( ...
    kOmegaA8T1(:,1), ...
    kOmegaA8T1(:,2), ...
    smoothingParameter ...
    );

kOmegaA8T1_Static = ppval( ...
    kOmegaA8T1_SplineStatic, ...
    CLalphaOmegaFracClmax ...
    );

%% taperRatio = 0.3 AR = 20
smoothingParameter = 0.999999;
kOmegaA20T0p3_SplineStatic = csaps( ...
    kOmegaA20T0p3(:,1), ...
    kOmegaA20T0p3(:,2), ...
    smoothingParameter ...
    );

kOmegaA20T0p3_Static = ppval( ...
    kOmegaA20T0p3_SplineStatic, ...
    CLalphaOmegaFracClmax ...
    );

%% taperRatio = 0.4 AR = 20
smoothingParameter = 0.999999;
kOmegaA20T0p4_SplineStatic = csaps( ...
    kOmegaA20T0p4(:,1), ...
    kOmegaA20T0p4(:,2), ...
    smoothingParameter ...
    );

kOmegaA20T0p4_Static = ppval( ...
    kOmegaA20T0p4_SplineStatic, ...
    CLalphaOmegaFracClmax ...
    );

%% taperRatio = 0.5 AR = 20
smoothingParameter = 0.999999;
kOmegaA20T0p5_SplineStatic = csaps( ...
    kOmegaA20T0p5(:,1), ...
    kOmegaA20T0p5(:,2), ...
    smoothingParameter ...
    );

kOmegaA20T0p5_Static = ppval( ...
    kOmegaA20T0p5_SplineStatic, ...
    CLalphaOmegaFracClmax ...
    );

%% taperRatio = 0.6 AR = 20
smoothingParameter = 0.999999;
kOmegaA20T0p6_SplineStatic = csaps( ...
    kOmegaA20T0p6(:,1), ...
    kOmegaA20T0p6(:,2), ...
    smoothingParameter ...
    );

kOmegaA20T0p6_Static = ppval( ...
    kOmegaA20T0p6_SplineStatic, ...
    CLalphaOmegaFracClmax ...
    );

%% taperRatio = 0.7 AR = 20
smoothingParameter = 0.999999;
kOmegaA20T0p7_SplineStatic = csaps( ...
    kOmegaA20T0p7(:,1), ...
    kOmegaA20T0p7(:,2), ...
    smoothingParameter ...
    );

kOmegaA20T0p7_Static = ppval( ...
    kOmegaA20T0p7_SplineStatic, ...
    CLalphaOmegaFracClmax ...
    );

%% taperRatio = 0.8 AR = 20
smoothingParameter = 0.999999;
kOmegaA20T0p8_SplineStatic = csaps( ...
    kOmegaA20T0p8(:,1), ...
    kOmegaA20T0p8(:,2), ...
    smoothingParameter ...
    );

kOmegaA20T0p8_Static = ppval( ...
    kOmegaA20T0p8_SplineStatic, ...
    CLalphaOmegaFracClmax ...
    )

%% taperRatio = 0.9 AR = 20
smoothingParameter = 0.999999;
kOmegaA20T0p9_SplineStatic = csaps( ...
    kOmegaA20T0p9(:,1), ...
    kOmegaA20T0p9(:,2), ...
    smoothingParameter ...
    );

kOmegaA20T0p9_Static = ppval( ...
    kOmegaA20T0p9_SplineStatic, ...
    CLalphaOmegaFracClmax ...
    );

%% taperRatio = 1 AR = 20
smoothingParameter = 0.999999;
kOmegaA20T1_SplineStatic = csaps( ...
    kOmegaA20T1(:,1), ...
    kOmegaA20T1(:,2), ...
    smoothingParameter ...
    );

kOmegaA20T1_Static = ppval( ...
    kOmegaA20T1_SplineStatic, ...
    CLalphaOmegaFracClmax ...
    );

%% Plots
figure(1)
plot ( ...
    CLalphaOmegaFracClmax, kOmegaA4T0p3_Static, 'b-+' ... , ...
 );
 hold on
 
 plot ( ...
    CLalphaOmegaFracClmax, kOmegaA4T0p4_Static, 'b-o' ... , ...
 );

hold on

plot ( ...
    CLalphaOmegaFracClmax, kOmegaA4T0p5_Static, 'b-*' ... , ...
 );

hold on

plot ( ...
    CLalphaOmegaFracClmax, kOmegaA4T0p6_Static, 'b-.' ... , ...
 );

hold on

plot ( ...
    CLalphaOmegaFracClmax, kOmegaA4T0p7_Static, 'b-x' ... , ...
 );

hold on

plot ( ...
    CLalphaOmegaFracClmax, kOmegaA4T0p8_Static, 'b-^' ... , ...
 );
hold on

plot ( ...
    CLalphaOmegaFracClmax, kOmegaA4T0p9_Static, 'b-v' ... , ...
 );
hold on

plot ( ...
    CLalphaOmegaFracClmax, kOmegaA4T1_Static, 'b' ... , ...
 );

 xlabel('(C_{L\alpha}\Omega)/C{l,max}'); ylabel('K_\Omega');
 title('K_{\Omega} coefficient variation with (C_{L\alpha}\Omega)/C{l,max} at different taper ratio and AR = 4');
  legend('\lambda = 0.3', '\lambda = 0.4', '\lambda = 0.5', '\lambda = 0.6', ...
         '\lambda = 0.7', '\lambda = 0.8', '\lambda = 0.9', '\lambda = 1.0');
 axis([0 0.5 -0.225 0.425]);
 grid on;
 
 figure(2)
plot ( ...
    CLalphaOmegaFracClmax, kOmegaA8T0p3_Static, 'b-+' ... , ...
 );
 hold on
 
 plot ( ...
    CLalphaOmegaFracClmax, kOmegaA8T0p4_Static, 'b-o' ... , ...
 );

hold on

plot ( ...
    CLalphaOmegaFracClmax, kOmegaA8T0p5_Static, 'b-*' ... , ...
 );

hold on

plot ( ...
    CLalphaOmegaFracClmax, kOmegaA8T0p6_Static, 'b-.' ... , ...
 );

hold on

plot ( ...
    CLalphaOmegaFracClmax, kOmegaA8T0p7_Static, 'b-x' ... , ...
 );

hold on

plot ( ...
    CLalphaOmegaFracClmax, kOmegaA8T0p8_Static, 'b-^' ... , ...
 );
hold on

plot ( ...
    CLalphaOmegaFracClmax, kOmegaA8T0p9_Static, 'b-v' ... , ...
 );
hold on

plot ( ...
    CLalphaOmegaFracClmax, kOmegaA8T1_Static, 'b' ... , ...
 );

 xlabel('(C_{L\alpha}\Omega)/C{l,max}'); ylabel('K_\Omega');
 title('K_{\Omega} coefficient variation with (C_{L\alpha}\Omega)/C{l,max} at different taper ratio and AR = 8');
  legend('\lambda = 0.3', '\lambda = 0.4', '\lambda = 0.5', '\lambda = 0.6', ...
         '\lambda = 0.7', '\lambda = 0.8', '\lambda = 0.9', '\lambda = 1.0');
 axis([0 0.5 -0.225 0.425]);
 grid on;
 
 figure(3)
plot ( ...
    CLalphaOmegaFracClmax, kOmegaA20T0p3_Static, 'b-+' ... , ...
 );
 hold on
 
 plot ( ...
    CLalphaOmegaFracClmax, kOmegaA20T0p4_Static, 'b-o' ... , ...
 );

hold on

plot ( ...
    CLalphaOmegaFracClmax, kOmegaA20T0p5_Static, 'b-*' ... , ...
 );

hold on

plot ( ...
    CLalphaOmegaFracClmax, kOmegaA20T0p6_Static, 'b-.' ... , ...
 );

hold on

plot ( ...
    CLalphaOmegaFracClmax, kOmegaA20T0p7_Static, 'b-x' ... , ...
 );

hold on

plot ( ...
    CLalphaOmegaFracClmax, kOmegaA20T0p8_Static, 'b-^' ... , ...
 );
hold on

plot ( ...
    CLalphaOmegaFracClmax, kOmegaA20T0p9_Static, 'b-v' ... , ...
 );
hold on

plot ( ...
    CLalphaOmegaFracClmax, kOmegaA20T1_Static, 'b' ... , ...
 );

 xlabel('(C_{L\alpha}\Omega)/C{l,max}'); ylabel('K_\Omega');
 title('K_{\Omega} coefficient variation with (C_{L\alpha}\Omega)/C{l,max} at different taper ratio and AR = 20');
  legend('\lambda = 0.3', '\lambda = 0.4', '\lambda = 0.5', '\lambda = 0.6', ...
         '\lambda = 0.7', '\lambda = 0.8', '\lambda = 0.9', '\lambda = 1.0');
 axis([0 0.5 -0.225 0.425]);
 grid on;
 
 %% preparing output to HDF

% var 1
taperRatioVector = [ ...
    0.3;0.4;0.5;0.6;0.7;0.8;0.9;1.0 ...
    ];

% var 0
aspectRatioVector = [ ...
    4;8;20 ...
    ];

%columns --> curves
myData(:,:,1) = [kOmegaA4T0p3_Static, ...
                 kOmegaA4T0p4_Static, ...
                 kOmegaA4T0p5_Static, ...
                 kOmegaA4T0p6_Static, ...
                 kOmegaA4T0p7_Static, ...
                 kOmegaA4T0p8_Static, ...
                 kOmegaA4T0p9_Static, ...
                 kOmegaA4T1_Static ...
                 ];
myData(:,:,2) = [kOmegaA8T0p3_Static, ...
                 kOmegaA8T0p4_Static, ...
                 kOmegaA8T0p5_Static, ...
                 kOmegaA8T0p6_Static, ...
                 kOmegaA8T0p7_Static, ...
                 kOmegaA8T0p8_Static, ...
                 kOmegaA8T0p9_Static, ...
                 kOmegaA8T1_Static ...
                 ];
myData(:,:,3) = [kOmegaA20T0p3_Static, ...
                 kOmegaA20T0p4_Static, ...
                 kOmegaA20T0p5_Static, ...
                 kOmegaA20T0p6_Static, ...
                 kOmegaA20T0p7_Static, ...
                 kOmegaA20T0p8_Static, ...
                 kOmegaA20T0p9_Static, ...
                 kOmegaA20T1_Static ...
                 ];

myData = permute(myData, [3 2 1]);             
             
hdfFileName = 'K_Omega_vs_CLalphaOmegaFracClmax_(taperRatio)_(AR).h5';

if ( exist(hdfFileName, 'file') )
    fprintf('file %s exists, deleting and creating a new one\n', hdfFileName);
    delete(hdfFileName)
else
    fprintf('Creating new file %s\n', hdfFileName);
end

% Dataset: data
h5create(hdfFileName, '/K_Omega_vs_CLalphaOmegaFracClmax_(taperRatio)_(AR)/data', size(myData));
h5write(hdfFileName, '/K_Omega_vs_CLalphaOmegaFracClmax_(taperRatio)_(AR)/data', myData);

% Dataset: var_0
h5create(hdfFileName, '/K_Omega_vs_CLalphaOmegaFracClmax_(taperRatio)_(AR)/var_0', size(aspectRatioVector'));
h5write(hdfFileName, '/K_Omega_vs_CLalphaOmegaFracClmax_(taperRatio)_(AR)/var_0', aspectRatioVector');

% Dataset: var_1
h5create(hdfFileName, '/K_Omega_vs_CLalphaOmegaFracClmax_(taperRatio)_(AR)/var_1', size(taperRatioVector'));
h5write(hdfFileName, '/K_Omega_vs_CLalphaOmegaFracClmax_(taperRatio)_(AR)/var_1', taperRatioVector');

% Dataset: var_2
h5create(hdfFileName, '/K_Omega_vs_CLalphaOmegaFracClmax_(taperRatio)_(AR)/var_2', size(CLalphaOmegaFracClmax'));
h5write(hdfFileName, '/K_Omega_vs_CLalphaOmegaFracClmax_(taperRatio)_(AR)/var_2', CLalphaOmegaFracClmax');