/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.HalfedgeDS;
import CGAL.Kernel.Point_2;
public class HalfedgeDS_modifier {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public HalfedgeDS_modifier(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(HalfedgeDS_modifier obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_HalfedgeDSJNI.delete_HalfedgeDS_modifier(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public HalfedgeDS_modifier() {
    this(CGAL_HalfedgeDSJNI.new_HalfedgeDS_modifier(), true);
  }

  public void begin_surface(int v, int f, int h, Modifier_mode mode) {
    CGAL_HalfedgeDSJNI.HalfedgeDS_modifier_begin_surface__SWIG_0(swigCPtr, this, v, f, h, mode.swigValue());
  }

  public void begin_surface(int v, int f, int h) {
    CGAL_HalfedgeDSJNI.HalfedgeDS_modifier_begin_surface__SWIG_1(swigCPtr, this, v, f, h);
  }

  public void begin_surface(int v, int f) {
    CGAL_HalfedgeDSJNI.HalfedgeDS_modifier_begin_surface__SWIG_2(swigCPtr, this, v, f);
  }

  public void end_surface() {
    CGAL_HalfedgeDSJNI.HalfedgeDS_modifier_end_surface(swigCPtr, this);
  }

  public void add_vertex(Point_2 p) {
    CGAL_HalfedgeDSJNI.HalfedgeDS_modifier_add_vertex(swigCPtr, this, Point_2.getCPtr(p), p);
  }

  public void begin_facet() {
    CGAL_HalfedgeDSJNI.HalfedgeDS_modifier_begin_facet(swigCPtr, this);
  }

  public void end_facet() {
    CGAL_HalfedgeDSJNI.HalfedgeDS_modifier_end_facet(swigCPtr, this);
  }

  public void add_vertex_to_facet(int i) {
    CGAL_HalfedgeDSJNI.HalfedgeDS_modifier_add_vertex_to_facet(swigCPtr, this, i);
  }

  public void rollback() {
    CGAL_HalfedgeDSJNI.HalfedgeDS_modifier_rollback(swigCPtr, this);
  }

  public void clear() {
    CGAL_HalfedgeDSJNI.HalfedgeDS_modifier_clear(swigCPtr, this);
  }

}
