This is makeindex, version 2.15 [TeX Live 2017/W32TeX] (kpathsea + Thai support).
Scanning style file ./Tesi.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Tesi.acn....done (308 entries accepted, 0 rejected).
Sorting entries.....done (2754 comparisons).
Generating output file Tesi.acr....done (159 lines written, 0 warnings).
Output written in Tesi.acr.
Transcript written in Tesi.alg.
